version: "3.7"
services:
  web:
    image: sabr_aml_am_web
    stop_grace_period: 1m
    stop_signal: SIGINT
    deploy:
      replicas: 1
    environment:
      - AILTIRE_STACKNAME={{.Service.Name}}-{{.Task.Slot}}
      - AILTIRE_SERVICENAME=web
      - AILTIRE_PARENT=${AILTIRE_APPNAME}
      - AILTIRE_PARENTHOST=admin
      - AILTIRE_APPNAME=${AILTIRE_APPNAME}
    networks:
      sibling:
      parent:
        aliases:
        - web
networks:
  sibling:
    driver: overlay
  parent:
    external: true
    name: ${AILTIRE_PARENT_NETWORK}

