@startuml

class "CapabilityInstance" as Model {
 string name

 deploy()
 kill()
 update()

}

rectangle "SABundleInstance" as SABundleInstance #lightblue {
}

Model o--> "n" SABundleInstance : bundles


rectangle "Capability" as Capability #lightblue {
}

Model o--> "1" Capability : owner


rectangle "Provisioner" as Provisioner #lightblue {
}

Model o--> "1" Provisioner : provisioner




    rectangle "Capability" as Capability #lightgreen {
    }

        Capability   *--> "n" Model : "instances"


@enduml
