@startuml



state CapabilityInstance #00aaff {

    state Init #00aaff {
    }

    state Created #00aaff {
    }

    state Deploying #00aaff {
    }

    state Deployed #00aaff {
    }

    state Disabled #00aaff {
    }

    state Destroyed #00aaff {
    }




Init -[#black]--> Created : create

Created -[#black]--> Deploying : deploy

Created -[#black]--> Destroyed : destroy

Deploying -[#black]--> Deployed : deployed

Deployed -[#black]--> Disabled : disable

Disabled -[#black]--> Deployed : enable

Disabled -[#black]--> Destroyed : destroy

}


@enduml
