@startuml

class "SABundle" as Model {
 string name
 string version

 create()
 deploy()
 toJScript()
 
}

rectangle "DataStream" as DataStream #lightblue {
}

Model o--> "n" DataStream : inputs


rectangle "DataStream" as DataStream #lightblue {
}

Model o--> "n" DataStream : outputs


rectangle "DataStream" as DataStream #lightblue {
}

Model o--> "1" DataStream : learningInput


rectangle "DataStream" as DataStream #lightblue {
}

Model o--> "1" DataStream : learningOutput


rectangle "DataStream" as DataStream #lightblue {
}

Model o--> "1" DataStream : adminStream


rectangle "DataStream" as DataStream #lightblue {
}

Model o--> "1" DataStream : admoutStream


rectangle "DataTransform" as DataTransform #lightblue {
}

Model o--> "n" DataTransform : transforms


rectangle "Application" as Application #lightblue {
}

Model o--> "n" Application : applications


rectangle "Stack" as Stack #lightblue {
}

Model o--> "n" Stack : stacks


rectangle "AIModel" as AIModel #lightblue {
}

Model o--> "n" AIModel : aimodels


rectangle "SABundleInstance" as SABundleInstance #lightblue {
}

Model *--> "n" SABundleInstance : instances




    rectangle "Capability" as Capability #lightgreen {
    }
    
        Capability   o--> "n" Model : "bundles"
    
    rectangle "DataStream" as DataStream #lightgreen {
    }
    
        DataStream   o--> "n" Model : "consumers"
    
    rectangle "DataStream" as DataStream #lightgreen {
    }
    
        DataStream   o--> "n" Model : "producers"
    
    rectangle "SABundleInstance" as SABundleInstance #lightgreen {
    }
    
        SABundleInstance   o--> "1" Model : "parent"
    

@enduml
