@startuml

class "ChannelActivationItem" as Model {
 string name
 number priority
 boolean activated

 
}

rectangle "DataChannel" as DataChannel #lightblue {
}

Model o--> "1" DataChannel : channel


rectangle "ChannelActivationPolicy" as ChannelActivationPolicy #lightblue {
}

Model o--> "1" ChannelActivationPolicy : parent




    rectangle "ChannelActivationPolicy" as ChannelActivationPolicy #lightgreen {
    }
    
        ChannelActivationPolicy   *--> "n" Model : "channels"
    

@enduml
