FROM jekyll/jekyll
# Create app directory
WORKDIR /srv/jekyll

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY . .
ENV JEKYLL_ENV=docker
RUN bundle
# RUN jekyll build --config _config.yml
EXPOSE 4000
CMD jekyll serve --config _config.yml
