FROM jekyll/jekyll

# Create app directory
WORKDIR /srv/jekyll

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY . .

EXPOSE 8088
CMD [ "sh" ]
