@startuml



state ApplicationInstance #00aaff {

    state Init #00aaff {
    }

    state Initializing #00aaff {
    }

    state Running #00aaff {
    }

    state Stopping #00aaff {
    }

    state Stopped #00aaff {
    }

    state Exit #00aaff {
    }

    state Failed #00aaff {
    }




Init -[#black]--> Initializing : create

Initializing -[#black]--> Running : provisoned

Running -[#black]--> Stopping : kill

Stopping -[#black]--> Stopped : stopped

Stopped -[#black]--> Exit : exit

Stopped -[#black]--> Failed : failed

}


@enduml
