version: "3.7"
services:
  pulsar:
    image: pulsar
    ports:
      - "6650:6650"
      - "8081:8080"
    networks:
      - children
  sabr1:
    image: sabr
    environment:
      - "PULSAR_ADMIN=tasks.pulsar:8080"
      - "PULSAR_HOST=tasks.pulsar:6650"
      - "SABR_DEF=./bundle1.js"
      - "SABR_POLICIES=./policies.js"
      - "SABR_NAME=sabr1"
    networks:
      - children
  sabr2:
    image: sabr
    environment:
      - "PULSAR_ADMIN=tasks.pulsar:8080"
      - "PULSAR_HOST=tasks.pulsar:6650"
      - "SABR_DEF=./bundle2.js"
      - "SABR_POLICIES=./policies.js"
      - "SABR_NAME=sabr2"
    networks:
      - children
  sabr3:
    image: sabr
    environment:
      - "PULSAR_ADMIN=tasks.pulsar:8080"
      - "PULSAR_HOST=tasks.pulsar:6650"
      - "SABR_DEF=./bundle3.js"
      - "SABR_POLICIES=./policies.js"
      - "SABR_NAME=sabr3"
    networks:
      - children
  sabr4:
    image: sabr
    environment:
      - "PULSAR_ADMIN=tasks.pulsar:8080"
      - "PULSAR_HOST=tasks.pulsar:6650"
      - "SABR_DEF=./bundle4.js"
      - "SABR_POLICIES=./policies.js"
      - "SABR_NAME=sabr4"
    networks:
      - children
networks:
  children:
    driver: overlay
