version: "3.7"
services:
  pulsar:
    image: apachepulsar/pulsar-all:latest
    ports:
      - "6650:6650"
      - "8081:8080"
    networks:
      - children
    command: "bin/pulsar standalone"
networks:
  children:
    driver: overlay
