@startuml
  interface CLI
  interface Web
  interface WebSocket
package "Sentient Agent Bundle Resources" #bbaaff {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component " sabr" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\n" as sabr_container
      REST --> sabr_container

  
    file "sabrweb" as sabrweb_container
    REST --> sabrweb_container
    socket ---> sabrweb_container
  
    file "pulsar" as pulsar_container
    REST --> pulsar_container
    socket ---> pulsar_container
  
    file "doc" as doc_container
    REST --> doc_container
    socket ---> doc_container
  
  }
  folder images #ffffff {
    collections "sabr" as sabrimage
    artifact "ailtire:swarm" as ailtireswarm
    sabrimage <|-- ailtireswarm
    sabr_container --> sabrimage

  
      artifact "sabr_web" as sabr_web
      sabrweb_container --> sabr_web
    
      artifact "sabr_pulsar:standalone" as sabr_pulsar_standalone
      pulsar_container --> sabr_pulsar_standalone
    
      artifact "sabr_doc" as sabr_doc
      doc_container --> sabr_doc
    
  }
}
CLI " sabr" -- binName
Web "/sabr" - REST
WebSocket ".sabr" -- socket

@enduml
