@startuml

actor "ApplicationDeveloper"


entity EventBus

box Sentient Agent Bundle Resources #bbaaff
    boundary sabr #white
end box


box Sentient Agent Bundle Resources #bbaaff
    end box

box Sentient Agent Bundle Manager #ffcc88
    end box


"ApplicationDeveloper" -> sabr: USV One Instance

    sabr -> "sentient agent bundle resources": create (name: Ship1,file: ./projects/AISSimulator/AISShip/bundle.js)

    "sentient agent bundle resources" --/ EventBus: bundle.create

    sabr -> "sentient agent bundle resources": create (name: USV,file: ./projects/AISSimulator/AISUSV/bundle.js)

    "sentient agent bundle resources" --/ EventBus: bundle.create

    sabr -> "sentient agent bundle resources": create (name: Agg1,file: ./projects/AISSimulator/AISAgg/bundle.js)

    "sentient agent bundle resources" --/ EventBus: bundle.create

    sabr -> "sentient agent bundle resources": create (name: Viewer1,file: ./projects/AISSimulator/AISViewer/bundle.js)

    "sentient agent bundle resources" --/ EventBus: bundle.create

    sabr -> "sentient agent bundle manager": create (file: ./projects/AISSimulator/AISShip/policies.js)

    "sentient agent bundle manager" --/ EventBus: policy.create

    sabr -> "sentient agent bundle manager": deploy (sabr: Viewer1,policies: realtime)

    "sentient agent bundle manager" --/ EventBus: bundle.deploy

    sabr -> "sentient agent bundle manager": deploy (sabr: Agg1,policies: realtime)

    "sentient agent bundle manager" --/ EventBus: bundle.deploy

    sabr -> "sentient agent bundle manager": deploy (sabr: USV,policies: realtime,parameters: MMSI=215071000,sourceFiles=../AIS_Simulator/ships/215071000.csv:../AIS_Simulator/ships/367092720.csv:../AIS_Simulator/ships/367182840.csv:../AIS_Simulator/ships/367289000.csv:../AIS_Simulator/ships/367370780.csv:../AIS_Simulator/ships/367425680.csv:../AIS_Simulator/ships/367530120.csv:../AIS_Simulator/ships/367602610.csv:../AIS_Simulator/ships/367611060.csv:../AIS_Simulator/ships/368010420.csv:../AIS_Simulator/ships/368066140.csv:../AIS_Simulator/ships/368132890.csv:../AIS_Simulator/ships/368149330.csv:../AIS_Simulator/ships/368175820.csv:../AIS_Simulator/ships/368184020.csv:../AIS_Simulator/ships/368197440.csv:../AIS_Simulator/ships/372443000.csv:../AIS_Simulator/ships/538002220.csv:../AIS_Simulator/ships/538002784.csv:../AIS_Simulator/ships/636019418.csv)

    "sentient agent bundle manager" --/ EventBus: bundle.deploy



@enduml
