@startuml
left to right direction


state "aml" as aml #00aaff {
state "am" as amlam #00aaff {
}
}


state "amlam" as pstatename #00aaff {
    state "Custom Function" as amfunction {
    }
}

        state "aml" as aml #00aaff {
state "am" as amlam #00aaff {
state "application" as amlamapplication #00aaff {
state "create" as amlamapplicationcreate #00aaff {
}
}
}
}


        state "aml" as aml #00aaff {
state "am" as amlam #00aaff {
state "application" as amlamapplication #00aaff {
state "destroy" as amlamapplicationdestroy #00aaff {
}
}
}
}


        state "aml" as aml #00aaff {
state "am" as amlam #00aaff {
state "application" as amlamapplication #00aaff {
state "list" as amlamapplicationlist #00aaff {
}
}
}
}


        state "aml" as aml #00aaff {
state "am" as amlam #00aaff {
state "application" as amlamapplication #00aaff {
state "update" as amlamapplicationupdate #00aaff {
}
}
}
}


        state "aml" as aml #00aaff {
state "am" as amlam #00aaff {
state "service" as amlamservice #00aaff {
state "deployed" as amlamservicedeployed #00aaff {
}
}
}
}


        state "aml" as aml #00aaff {
state "am" as amlam #00aaff {
state "service" as amlamservice #00aaff {
state "kill" as amlamservicekill #00aaff {
}
}
}
}


        state "aml" as aml #00aaff {
state "am" as amlam #00aaff {
state "service" as amlamservice #00aaff {
state "provision" as amlamserviceprovision #00aaff {
}
}
}
}


        state "aml" as aml #00aaff {
state "am" as amlam #00aaff {
state "service" as amlamservice #00aaff {
state "stderr" as amlamservicestderr #00aaff {
}
}
}
}


        state "aml" as aml #00aaff {
state "am" as amlam #00aaff {
state "service" as amlamservice #00aaff {
state "stdout" as amlamservicestdout #00aaff {
}
}
}
}




        state "aml" as aml #00aaff {
state "am" as amlam #00aaff {
state "ServiceInstance" as amlamserviceinstance #00aaff {
state "deployed" as amlamserviceinstancedeployed #00aaff {
}
}
}
}

        
    state "aml" as aml #00aaff {
state "am" as amlam #00aaff {
state "service" as amlamservice #00aaff {
state "provision" as amlamserviceprovision #00aaff {
}
}
}
}

    amlamserviceinstancedeployed ---> amlamserviceprovision
  

        state "aml" as aml #00aaff {
state "am" as amlam #00aaff {
state "ServiceInstance" as amlamserviceinstance #00aaff {
state "killed" as amlamserviceinstancekilled #00aaff {
}
}
}
}

        
    state "aml" as aml #00aaff {
state "am" as amlam #00aaff {
state "Function" as amlamfunction #00aaff {
}
}
}

    amlamserviceinstancekilled ---> amlamfunction
  


    
    
        
       
    
    
        
       

@enduml
