@startuml
left to right direction


    package "sabr" as sabr {
package "aml" as sabraml {
package "am" as sabramlam #00aaff {
 component "application" as sabramlamapplication
 interface "create" as sabramlamapplicationcreate
sabramlamapplication -- sabramlamapplicationcreate
}
}
}

    
    package "sabr" as sabr {
package "aml" as sabraml {
package "am" as sabramlam #00aaff {
 component "application" as sabramlamapplication
 interface "destroy" as sabramlamapplicationdestroy
sabramlamapplication -- sabramlamapplicationdestroy
}
}
}

    
    package "sabr" as sabr {
package "aml" as sabraml {
package "am" as sabramlam #00aaff {
 component "application" as sabramlamapplication
 interface "list" as sabramlamapplicationlist
sabramlamapplication -- sabramlamapplicationlist
}
}
}

    
    package "sabr" as sabr {
package "aml" as sabraml {
package "am" as sabramlam #00aaff {
 component "application" as sabramlamapplication
 interface "update" as sabramlamapplicationupdate
sabramlamapplication -- sabramlamapplicationupdate
}
}
}

    
    package "sabr" as sabr {
package "aml" as sabraml {
package "am" as sabramlam #00aaff {
 component "service" as sabramlamservice
 interface "deployed" as sabramlamservicedeployed
sabramlamservice -- sabramlamservicedeployed
}
}
}

    
    package "sabr" as sabr {
package "aml" as sabraml {
package "am" as sabramlam #00aaff {
 component "service" as sabramlamservice
 interface "kill" as sabramlamservicekill
sabramlamservice -- sabramlamservicekill
}
}
}

    
    package "sabr" as sabr {
package "aml" as sabraml {
package "am" as sabramlam #00aaff {
 component "service" as sabramlamservice
 interface "provision" as sabramlamserviceprovision
sabramlamservice -- sabramlamserviceprovision
}
}
}

    
    package "sabr" as sabr {
package "aml" as sabraml {
package "am" as sabramlam #00aaff {
 component "service" as sabramlamservice
 interface "stderr" as sabramlamservicestderr
sabramlamservice -- sabramlamservicestderr
}
}
}

    
    package "sabr" as sabr {
package "aml" as sabraml {
package "am" as sabramlam #00aaff {
 component "service" as sabramlamservice
 interface "stdout" as sabramlamservicestdout
sabramlamservice -- sabramlamservicestdout
}
}
}

    
hexagon "serviceinstance.deployed" as serviceinstancedeployed
            sabramlam <-- serviceinstancedeployed
        
hexagon "serviceinstance.killed" as serviceinstancekilled
            sabramlam <-- serviceinstancekilled
        


        rectangle "Manage Application" as ManageApplication #ffffaa {
            ("Create Application")/ as ApplicationDeveloperManageApplicationCreateApplication
        }
    
    sabramlamapplicationcreate <-- ApplicationDeveloperManageApplicationCreateApplication
    
        rectangle "Manage Application" as ManageApplication #ffffaa {
            ("Destroy Application")/ as DevOpsEngineerManageApplicationDestroyApplication
        }
    
    sabramlamapplicationdestroy <-- DevOpsEngineerManageApplicationDestroyApplication
    
        rectangle "Manage Application" as ManageApplication #ffffaa {
            ("Update Application")/ as DevOpsEngineerManageApplicationUpdateApplication
        }
    
    sabramlamapplicationupdate <-- DevOpsEngineerManageApplicationUpdateApplication
    












@enduml
