@startuml


package "Service Orchestrator" #aaffaa {

}

package "Application Manager" #00aaff {

}


package "Application Manager" #00aaff {

    interface "Application Manager" as i {
            ^serviceinstance.deployed
            ^serviceinstance.killed
    
            /sabr/aml/am/application/create()
            /sabr/aml/am/application/destroy()
            /sabr/aml/am/application/list()
            /sabr/aml/am/application/update()
            /sabr/aml/am/service/deployed()
            /sabr/aml/am/service/kill()
            /sabr/aml/am/service/provision()
            /sabr/aml/am/service/stderr()
            /sabr/aml/am/service/stdout()
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Application Manager" #00aaff {


}


    "Service Orchestrator" <-- "Application Manager"


@enduml
