@startuml



state DataChannel #ffcc88 {

    state Init #ffcc88 {
    }

    state Created #ffcc88 {
    }

    state Disabled #ffcc88 {
    }

    state Enabled #ffcc88 {
    }

    state Destroyed #ffcc88 {
    }




Init -[#black]--> Created : create

Created -[#black]--> Disabled : disable

Created -[#black]--> Destroyed : destroy

Disabled -[#black]--> Enabled : enable

Disabled -[#black]--> Destroyed : destroy

Enabled -[#black]--> Disabled : disbale

}


@enduml
