@startuml
  interface CLI
  interface Web
  interface WebSocket
package "Distributed Information Management Layer" #ffcc88 {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component " sabr diml" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\n" as sabr_diml_container
      REST --> sabr_diml_container


    file "web" as web_container
    REST --> web_container
    socket ---> web_container

  }
  folder images #ffffff {
    collections "sabr_diml" as sabr_dimlimage
    artifact "ailtire:swarm" as ailtireswarm
    sabr_dimlimage <|-- ailtireswarm
    sabr_diml_container --> sabr_dimlimage


      artifact "sabr_diml_web" as sabr_diml_web
      web_container --> sabr_diml_web

  }
}
CLI " sabr diml" -- binName
Web "/sabr/diml" - REST
WebSocket ".sabr.diml" -- socket

@enduml
