@startuml


usecase "Manage AI Model" as ManageAIModel #yellow

Actor "DataEngineer" as DataEngineer

DataEngineer --> ManageAIModel

Actor "Data Scientist" as DataScientist

DataScientist --> ManageAIModel

Actor "Data Analyst" as DataAnalyst

DataAnalyst --> ManageAIModel











@enduml
