@startuml

actor "DevOpsEngineer"


entity EventBus

box Application Manager #00aaff
    boundary am #white
end box



"DevOpsEngineer" -> am: Destroy Application

    am -> "am": destroy (name: hello)

    "am" --/ EventBus: application.destroy



@enduml
