@startuml

class "ProcessProvisioner" as Model {
 string name
 json config

 deploy()

}

rectangle "ServiceInstance" as ServiceInstance #lightblue {
}

Model o--> "n" ServiceInstance : services





@enduml
