@startuml

left to right direction


Actor "Actor" as Actor


rectangle "DevSecOpsManager" as dsom #00aaff {
        usecase "Manage Environments" as ManageEnvironments
    Actor --> ManageEnvironments

}


@enduml
