@startuml
  interface CLI
  interface Web
  interface WebSocket
package "Identity Aspect" #ffbbbb {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component " sabr ia" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\n" as sabr_ia_container
      REST --> sabr_ia_container


    file "web" as web_container
    REST --> web_container
    socket ---> web_container

  }
  folder images #ffffff {
    collections "sabr_ia" as sabr_iaimage
    artifact "ailtire:swarm" as ailtireswarm
    sabr_iaimage <|-- ailtireswarm
    sabr_ia_container --> sabr_iaimage


      artifact "sabr_ia_web" as sabr_ia_web
      web_container --> sabr_ia_web

  }
}
CLI " sabr ia" -- binName
Web "/sabr/ia" - REST
WebSocket ".sabr.ia" -- socket

@enduml
