@startuml
left to right direction


    package "sabr" as sabr #bbaaff {
 component "bundle" as sabrbundle
 interface "build" as sabrbundlebuild
sabrbundle -- sabrbundlebuild
}


    package "sabr" as sabr #bbaaff {
 component "pulsar" as sabrpulsar
 interface "streams" as sabrpulsarstreams
sabrpulsar -- sabrpulsarstreams
}


    package "sabr" as sabr #bbaaff {
 component "pulsar" as sabrpulsar
 interface "topic" as sabrpulsartopic
sabrpulsar -- sabrpulsartopic
}


    package "sabr" as sabr #bbaaff {
 component "pulsar" as sabrpulsar
 interface "topics" as sabrpulsartopics
sabrpulsar -- sabrpulsartopics
}
















@enduml
