@startuml

left to right direction


boundary parent #black


entity children #blue




package "a_d" #00aaff {
    queue parentnet #black [
            <b><color:white>parent</color></b>
    ]

    parentnet -[#black]- parent

    queue childrennet #blue [
            <b><color:white>children</color></b>
    ]

    childrennet -[#blue]- children

    queue siblingsnet #red [
            <b><color:white>siblings</color></b>
    ]


node "web" as webService


        artifact "a_d_web" as a_d_webimage

}

webService -[#red]- siblingsnet
webService .... a_d_webimage


@enduml
