@startuml

left to right direction


boundary appname__family #red


entity appname__so_family #black




package "_so" #aaffaa {
    queue childrennet #black [
            <b><color:white>children</color></b>
    ]
    
    childrennet -[#black]- appname__so_family
    
    queue siblingnet #blue [
            <b><color:white>sibling</color></b>
    ]
    
    queue parentnet #red [
            <b><color:white>parent</color></b>
    ]
    
    parentnet -[#red]- appname__family
    

node "child" as childService
node "frontend" as frontendService
node "gw" as gwService


        artifact "child_image:latest" as child_imagelatestimage
    
        artifact "_so_web" as _so_webimage
    
        artifact "_so_gw" as _so_gwimage
    
}

childService -[#black]- childrennet

childService -[#red]- parentnet

frontendService -[#blue]- siblingnet

gwService -[#black]- childrennet

gwService -[#blue]- siblingnet
childService .... child_imagelatestimage
frontendService .... _so_webimage
gwService .... _so_gwimage


@enduml
