@startuml
  interface CLI
  interface Web
  interface WebSocket
package "DevSecOpsManager" #00aaff {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component " sabr aml dsom" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\ndocker-compose.yml" as devops_container
      REST --> devops_container

  
    file "web" as web_container
    REST --> web_container
    socket ---> web_container
  
  }
  folder images #ffffff {
    collections "devops" as devopsimage
    artifact "ailtire:swarm" as ailtireswarm
    devopsimage <|-- ailtireswarm
    devops_container --> devopsimage

  
      artifact "devops" as devops
      web_container --> devops
    
  }
}
CLI " sabr aml dsom" -- binName
Web "/sabr/aml/dsom" - REST
WebSocket ".sabr.aml.dsom" -- socket

@enduml
