@startuml
interface "CLI"
interface "REST"
interface "WebSocket"
interface "Web"
stack "Service Stack" #lightblue {
component  "Admin Container" as Admin
component "Stack 1" as C1 #dddddd
component "Container 2" as C2 #white
component "Container n" as Cn #white
database "Secret Vault" as vault
database "Stack Data" as sd #white
stack "Service Stack 1" as SS1 #dddddd
}
C2 .. sd
Cn .. sd
C1 .. sd
C1 --> SS1
Admin --> C1
Admin --> C2
Admin --> Cn
CLI -left-  Admin
REST --  Admin
WebSocket --  Admin
Web --  Admin
@enduml
