@startuml



package "Edge Security Controller" #ffcccc {

    interface "Edge Security Controller" as i {
            /sabr/sa/esc/bundle/deploy()
            /sabr/sa/esc/key/store()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Edge Security Controller" #ffcccc {
    
}



@enduml
