@startuml
left to right direction


state "sa" as sa #pink {
state "esc" as saesc #ffcccc {
}
}


state "saesc" as pstatename #ffcccc {
    state "Custom Function" as escfunction {
    }
}

        state "sa" as sa #pink {
state "esc" as saesc #ffcccc {
state "bundle" as saescbundle #ffcccc {
state "deploy" as saescbundledeploy #ffcccc {
}
}
}
}


        state "sa" as sa #pink {
state "esc" as saesc #ffcccc {
state "key" as saesckey #ffcccc {
state "store" as saesckeystore #ffcccc {
}
}
}
}






@enduml
