@startuml
left to right direction


    package "sabr" as sabr {
package "sa" as sabrsa {
package "esc" as sabrsaesc #lightblue {
 component "bundle" as sabrsaescbundle
 interface "deploy" as sabrsaescbundledeploy
sabrsaescbundle -- sabrsaescbundledeploy
}
}
}


    package "sabr" as sabr {
package "sa" as sabrsa {
package "esc" as sabrsaesc #lightblue {
 component "key" as sabrsaesckey
 interface "store" as sabrsaesckeystore
sabrsaesckey -- sabrsaesckeystore
}
}
}
















@enduml
