@startuml
  interface CLI
  interface Web
  interface WebSocket
package "Common Physical Layer" #lightgray {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component " sabr cpl" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\ndocker-compose.yml" as _cpl_container
      REST --> _cpl_container

  
    file "web" as web_container
    REST --> web_container
    socket ---> web_container
  
    file "gateway" as gateway_container
    REST --> gateway_container
    socket ---> gateway_container
  
  }
  folder images #ffffff {
    collections "_cpl" as _cplimage
    artifact "ailtire:swarm" as ailtireswarm
    _cplimage <|-- ailtireswarm
    _cpl_container --> _cplimage

  
      artifact _cpl_web
      web_container --> _cpl_web
    
      artifact _cpl_gw
      gateway_container --> _cpl_gw
    
  }
}
CLI " sabr cpl" -- binName
Web "/sabr/cpl" - REST
WebSocket ".sabr.cpl" -- socket

@enduml
