@startuml

class "Provisioner" as Model {
 string name
 json config


}

rectangle "ServiceInstance" as ServiceInstance #lightblue {
}

Model o--> "n" ServiceInstance : services




    rectangle "CapabilityInstance" as CapabilityInstance #lightgreen {
    }

        CapabilityInstance   o--> "1" Model : "provisioner"


@enduml
