@startuml

actor "DevOpsEngineer"


entity EventBus

box Capability Manager #00aaff
    boundary cm #white
end box


box Capability Manager #00aaff
            participant capability
    end box


"DevOpsEngineer" -> cm: Release Capability

    cm -> "capability": create (name: myCapabilityT1,file: ./templates/capability.js)

    "capability" --/ EventBus: capability.create

    cm -> "capability manager": build (name: myCapabilityT1)

    "capability manager" --/ EventBus: capability.build

    cm -> "capability manager": test (name: myCapabilityT1)

    "capability manager" --/ EventBus: capability.test

    cm -> "capability manager": release (name: myCapabilityT1)

    "capability manager" --/ EventBus: capability.release



@enduml
