@startuml

left to right direction


boundary appname__family #red


entity appname__cpl_family #black




package "_cpl" #lightgray {
    queue childrennet #black [
            <b><color:white>children</color></b>
    ]
    
    childrennet -[#black]- appname__cpl_family
    
    queue siblingnet #blue [
            <b><color:white>sibling</color></b>
    ]
    
    queue parentnet #red [
            <b><color:white>parent</color></b>
    ]
    
    parentnet -[#red]- appname__family
    

node "child" as childService
node "frontend" as frontendService
node "gw" as gwService


        artifact "child_image:latest" as child_imagelatestimage
    
        artifact "_cpl_web" as _cpl_webimage
    
        artifact "_cpl_gw" as _cpl_gwimage
    
}

childService -[#black]- childrennet

childService -[#red]- parentnet

frontendService -[#blue]- siblingnet

gwService -[#black]- childrennet

gwService -[#blue]- siblingnet
childService .... child_imagelatestimage
frontendService .... _cpl_webimage
gwService .... _cpl_gwimage


@enduml
