@startuml

class "Environment" as Model {
 string name

 
}

rectangle "Build" as Build #lightblue {
}

Model o--> "n" Build : builds


rectangle "BuildRun" as BuildRun #lightblue {
}

Model o--> "n" BuildRun : runs





@enduml
