@startuml


usecase "Manage Capabilities" as ManageCapabilities #yellow

Actor "DevOps Engineer" as DevOpsEngineer

DevOpsEngineer --> ManageCapabilities

Actor "IT Operations" as ITOperations

ITOperations --> ManageCapabilities







usecase "DeployCapability" as DeployCapability #lightyellow

ManageCapabilities --> DeployCapability : extends

usecase "DevelopCapability" as DevelopCapability #lightyellow

ManageCapabilities --> DevelopCapability : extends

usecase "RemoveCapbility" as RemoveCapbility #lightyellow

ManageCapabilities --> RemoveCapbility : extends

usecase "UpdateCapbility" as UpdateCapbility #lightyellow

ManageCapabilities --> UpdateCapbility : extends





@enduml
