@startuml



package "DevSecOpsManager" #00aaff {

    interface "DevSecOpsManager" as i {
            /sabr/aml/dsom/data/create()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "DevSecOpsManager" #00aaff {
        class "Environment" {
                 string attr1
                    }
                Environment o--> "1" ModelName : assoc1
            
    

}



@enduml
