@startuml


package "Data Stream Manager" #ffcc88 {

}

package "Sentient Agent Bundle Manager" #ffcc88 {

}

package "Application Manager" #00aaff {

}

package "Security Aspect" #pink {

}


package "Data Stream Manager" #ffcc88 {

    interface "Data Stream Manager" as i {
            ^inputchannelinstance.enabled
            ^inputstreaminstance.enabled
            ^outputchannelinstance.enabled
            ^outputstreaminstance.enabled
    
            /sabr/diml/dsm/channel/deployed()
            /sabr/diml/dsm/stream/deployed()
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Data Stream Manager" #ffcc88 {


}



@enduml
