@startuml
  interface CLI
  interface Web
  interface WebSocket
package "Application Manager" #00aaff {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component " sabr aml am" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\ndocker-compose.yml" as _am_container
      REST --> _am_container

  
    file "web" as web_container
    REST --> web_container
    socket ---> web_container
  
    file "gateway" as gateway_container
    REST --> gateway_container
    socket ---> gateway_container
  
  }
  folder images #ffffff {
    collections "_am" as _amimage
    artifact "ailtire:swarm" as ailtireswarm
    _amimage <|-- ailtireswarm
    _am_container --> _amimage

  
      artifact _am_web
      web_container --> _am_web
    
      artifact _am_gw
      gateway_container --> _am_gw
    
  }
}
CLI " sabr aml am" -- binName
Web "/sabr/aml/am" - REST
WebSocket ".sabr.aml.am" -- socket

@enduml
