version: "3.7"
services:
  pulsar:
    image: pulsar
    ports:
      - "6650:6650"
      - "8081:8080"
    networks:
      - children
  sabr1:
    image: sabr
    environment:
      - "PULSAR_ADMIN=tasks.pulsar:8080"
      - "PULSAR_HOST=tasks.pulsar:6650"
      - "SABR_STREAM=./streams.js"
      - "SABR_NAME=sabr1"
    networks:
      - children
  sabr2:
    image: sabr
    environment:
      - "PULSAR_ADMIN=tasks.pulsar:8080"
      - "PULSAR_HOST=tasks.pulsar:6650"
      - "SABR_STREAM=./streams2.js"
      - "SABR_NAME=sabr2"
    networks:
      - children
  sabr3:
    image: sabr
    environment:
      - "PULSAR_ADMIN=tasks.pulsar:8080"
      - "PULSAR_HOST=tasks.pulsar:6650"
      - "SABR_STREAM=./streams3.js"
      - "SABR_NAME=sabr3"
    networks:
      - children
networks:
  children:
    driver: overlay
