  web:
    image: sabr_
    interface:
      web:
        path: "/sabr"
        port: 3000
    networks:
      - children
      - siblings
  deviceagent:
    type: stack
    image: cpl_da
    interface:
      da:
        path: "/da"
        port: 3000
    volumes:
      docker:
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
    environment:
      EDGEMERE_TELEMETRY_NETWORK: _telemetry_family
    networks:
      - children
      - siblings
  devicemanager:
    type: stack
    image: cpl_dm
    interface:
      dm:
        path: "/dm"
        port: 3000
    volumes:
      docker:
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
    environment:
      EDGEMERE_TELEMETRY_NETWORK: _telemetry_family
    networks:
      - children
      - siblings
  telemetry:
    type: stack
    image: cpl_tc
    interface:
      telemetry:
        path: "/dm"
        port: 3000
    volumes:
      docker:
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
    environment:
      EDGEMERE_TELEMETRY_NETWORK: _telemetry_family
    networks:
      - children
      - parent
      - telemetry
interface:
  ports:
    80: 3000
    443: 3000
networks:
  telemetry:
    driver: overlay
    attachable: true
    name: _telemetry_family
data:
policies:
