version: "3.7"
services:
  sabr:
    image: sabr:latest
    ports:
      - '80:3000'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AILTIRE_PARENT_NETWORK=sabr_top
      - AILTIRE_STACKNAME={{.Service.Name}}-{{.Task.Slot}}
      - AILTIRE_APPNAME=sabr
    networks:
      children:
        aliases:
          - admin
networks:
  children:
    driver: overlay
    attachable: true
    name: sabr_top
