#!/user/bin/env node
const bent = require('bent');
const program = require('commander');
const YAML = require('yamljs');
const fs = require('fs');
global.ailtire = { config: require('/home/madajaju/work/sabr/bin/lib/../../.ailtire.js') };
program.description('Build the SAB with all of the elements including encrypting the bundle and the vault.')
	.option('--name <string>', 'The name of the Bundle.')
	.option('--id <string>', 'The id of the build.');
program.parse(process.argv);
let url = global.ailtire.config.host;
let args = {};
let params = '/diml/sabm/sabundle/build?';
params += 'mode=json';
let options = program.opts();

if(options['name']) { args['name'] = options['name']; }
if(options['id']) { args['id'] = options['id']; }

        console.log("URL:", url);
        console.log("Args:", args);
const post = bent(url, 'POST', 'json', 200);
(async () => {
    const response = await post(params, args);
    console.log("Response:", response);
})().catch(e => {
    // Deal with the fact the chain failed
    console.error("Response Error:", e);
});