#!/user/bin/env node
const bent = require('bent');
const program = require('commander');
const YAML = require('yamljs');
const fs = require('fs');
global.ailtire = { config: require('/home/madajaju/sabr/bin/lib/../../.ailtire.js') };
program.description('create entity')
	.option('--file <file>', 'file with the definition');
program.parse(process.argv);
let url = global.ailtire.config.host;
let args = {};
let params = '/diml/sabm/policy/create?';
params += 'mode=json';
let options = program.opts();

if(options['file']) { args['file'] = fs.readFileSync(options['file']); }

        console.log("URL:", url);
        console.log("Args:", args);
const post = bent(url, 'POST', 'json', 200);
(async () => {
    const response = await post(params, args);
    console.log("Response:", response);
})().catch(e => {
    // Deal with the fact the chain failed
    console.error("Response Error:", e);
});