#!/user/bin/env node
const bent = require('bent');
const program = require('commander');
const YAML = require('yamljs');
global.ailtire = { config: require('C:\\Users\\dwpulsip\\IdeaProjects\\sabr\\bin\\lib/../../.ailtire.js') };
program.description('create entity')
	.option('--name <string>', 'name of the capability')
	.option('--file <file>', 'file with the definition');
program.parse(process.argv);
let url = global.ailtire.config.host;
let args = {};
let params = '/capability/create?';
params += 'mode=json';
let options = program.opts();

if(program['name']) { args['name'] = program['name']; }
if(program['file']) { args['file'] = fs.readFileSync(program['file']); }

const post = bent(url, 'POST', 'json', 200);
(async () => {
    const response = await post(params, args);
    console.log("Response:", response);
})().catch(e => {
    // Deal with the fact the chain failed
    console.error("Response Error:", e);
});