#!/user/bin/env node
const bent = require('bent');
const program = require('commander');
const YAML = require('yamljs');
const fs = require('fs');
global.ailtire = { config: require('C:\\Users\\dwpulsip\\IdeaProjects\\sabr\\bin\\lib/../../.ailtire.js') };
program.description('Deploy a Capability')
	.option('--capability <string>', 'name of the capability');
program.parse(process.argv);
let url = global.ailtire.config.host;
let args = {};
let params = '/aml/cm/capability/deploy?';
params += 'mode=json';
let options = program.opts();

if(options['capability']) { args['capability'] = options['capability']; }

        console.log("URL:", url);
        console.log("Args:", args);
const post = bent(url, 'POST', 'json', 200);
(async () => {
    const response = await post(params, args);
    console.log("Response:", response);
})().catch(e => {
    // Deal with the fact the chain failed
    console.error("Response Error:", e);
});