#!/user/bin/env node
const bent = require('bent');
const program = require('commander');
const YAML = require('yamljs');
const fs = require('fs');
global.ailtire = { config: require('/home/madajaju/work/sabr/bin/lib/../../.ailtire.js') };
program.description('Deploy the bundle')
	.option('--sabr <string>', 'The name of the SABR')
	.option('--policies <string>', 'The name of the policies to use in the deployment. Comma separated')
	.option('--parameters <string>', 'Command Separate list of parameters name=value,...');
program.parse(process.argv);
let url = global.ailtire.config.host;
let args = {};
let params = '/diml/sabm/bundle/deploy?';
params += 'mode=json';
let options = program.opts();

if(options['sabr']) { args['sabr'] = options['sabr']; }
if(options['policies']) { args['policies'] = options['policies']; }
if(options['parameters']) { args['parameters'] = options['parameters']; }

        console.log("URL:", url);
        console.log("Args:", args);
const post = bent(url, 'POST', 'json', 200);
(async () => {
    const response = await post(params, args);
    console.log("Response:", response);
})().catch(e => {
    // Deal with the fact the chain failed
    console.error("Response Error:", e);
});