#!/user/bin/env node
const bent = require('bent');
const program = require('commander');
const YAML = require('yamljs');
const fs = require('fs');
global.ailtire = { config: require('C:\\Users\\dwpulsip\\IdeaProjects\\sabr\\bin\\lib/../../.ailtire.js') };
program.description('Update entity')
	.option('--name <string>', 'Name of the item to update')
	.option('--version <string>', 'Version of the Application')
	.option('--fn <ref>', 'Function to call with the bundle instance when the bundle instance is run.')
	.option('--id <string>', 'ID of the item to update');
program.parse(process.argv);
let url = global.ailtire.config.host;
let args = {};
let params = '/application/update?';
params += 'mode=json';
let options = program.opts();

if(options['name']) { args['name'] = options['name']; }
if(options['version']) { args['version'] = options['version']; }
if(options['fn']) { args['fn'] = options['fn']; }
if(options['id']) { args['id'] = options['id']; }

        console.log("URL:", url);
        console.log("Args:", args);
const post = bent(url, 'POST', 'json', 200);
(async () => {
    const response = await post(params, args);
    console.log("Response:", response);
})().catch(e => {
    // Deal with the fact the chain failed
    console.error("Response Error:", e);
});