@startuml
  interface CLI
  interface Web
  interface WebSocket
package "Application Management Layer" #00aaff {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component " sabr aml" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\n" as aml_container
      REST --> aml_container

  
  }
  folder images #ffffff {
    collections "aml" as amlimage
    artifact "ailtire:swarm" as ailtireswarm
    amlimage <|-- ailtireswarm
    aml_container --> amlimage

  
  }
}
CLI " sabr aml" -- binName
Web "/sabr/aml" - REST
WebSocket ".sabr.aml" -- socket

@enduml
