@startuml
  interface CLI
  interface Web
  interface WebSocket
package "Application Management Layer" #00aaff {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component " sabr aml" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\ndocker-compose.yml" as _aml_container
      REST --> _aml_container

  
    file "web" as web_container
    REST --> web_container
    socket ---> web_container
  
    file "gateway" as gateway_container
    REST --> gateway_container
    socket ---> gateway_container
  
  }
  folder images #ffffff {
    collections "_aml" as _amlimage
    artifact "ailtire:swarm" as ailtireswarm
    _amlimage <|-- ailtireswarm
    _aml_container --> _amlimage

  
      artifact _aml_web
      web_container --> _aml_web
    
      artifact _aml_gw
      gateway_container --> _aml_gw
    
  }
}
CLI " sabr aml" -- binName
Web "/sabr/aml" - REST
WebSocket ".sabr.aml" -- socket

@enduml
