@startuml

actor "DevOpsEngineer"


entity EventBus

box Sentient Agent Bundle Manager #ffcc88
    boundary sabm #white
end box


box Sentient Agent Bundle Manager #ffcc88
            participant sabundle
    end box

box Data Stream Manager #ffcc88
            participant streampolicy
    end box


"DevOpsEngineer" -> sabm: Deploy SABR

    sabm -> "sabundle": create (name: mySABR1,file: ./templates/bundle1.js)

    "sabundle" --/ EventBus: sabundle.create

    sabm -> "streampolicy": create (name: historical,file: ./templates/policy1.js)

    "streampolicy" --/ EventBus: streampolicy.create

    sabm -> "streampolicy": create (name: summary,file: ./templates/policy2.js)

    "streampolicy" --/ EventBus: streampolicy.create

    sabm -> "streampolicy": create (name: realtime,file: ./templates/policy3.js)

    "streampolicy" --/ EventBus: streampolicy.create

    sabm -> "sentient agent bundle manager": deploy (sabr: mySABR1,policies: realtime)

    "sentient agent bundle manager" --/ EventBus: bundle.deploy



@enduml
