@startuml
left to right direction


    package "sabr" as sabr {
package "diml" as sabrdiml {
 component "sabm" as sabrdimlsabm
 interface "connect" as sabrdimlsabmconnect
sabrdimlsabm -- sabrdimlsabmconnect
}
}


    package "sabr" as sabr {
package "diml" as sabrdiml {
package "sabm" as sabrdimlsabm #ffcc88 {
 component "bundle" as sabrdimlsabmbundle
 interface "createanddeploy" as sabrdimlsabmbundlecreateanddeploy
sabrdimlsabmbundle -- sabrdimlsabmbundlecreateanddeploy
}
}
}


    package "sabr" as sabr {
package "diml" as sabrdiml {
package "sabm" as sabrdimlsabm #ffcc88 {
 component "bundle" as sabrdimlsabmbundle
 interface "deploy" as sabrdimlsabmbundledeploy
sabrdimlsabmbundle -- sabrdimlsabmbundledeploy
}
}
}


    package "sabr" as sabr {
package "diml" as sabrdiml {
package "sabm" as sabrdimlsabm #ffcc88 {
 component "policy" as sabrdimlsabmpolicy
 interface "create" as sabrdimlsabmpolicycreate
sabrdimlsabmpolicy -- sabrdimlsabmpolicycreate
}
}
}


    package "sabr" as sabr {
package "diml" as sabrdiml {
package "sabm" as sabrdimlsabm #ffcc88 {
 component "sabundle" as sabrdimlsabmsabundle
 interface "build" as sabrdimlsabmsabundlebuild
sabrdimlsabmsabundle -- sabrdimlsabmsabundlebuild
}
}
}


    package "sabr" as sabr {
package "diml" as sabrdiml {
package "sabm" as sabrdimlsabm #ffcc88 {
 component "sabundle" as sabrdimlsabmsabundle
 interface "create" as sabrdimlsabmsabundlecreate
sabrdimlsabmsabundle -- sabrdimlsabmsabundlecreate
}
}
}


    package "sabr" as sabr {
package "diml" as sabrdiml {
package "sabm" as sabrdimlsabm #ffcc88 {
 component "sabundle" as sabrdimlsabmsabundle
 interface "deploy" as sabrdimlsabmsabundledeploy
sabrdimlsabmsabundle -- sabrdimlsabmsabundledeploy
}
}
}


    package "sabr" as sabr {
package "diml" as sabrdiml {
package "sabm" as sabrdimlsabm #ffcc88 {
 component "sabundle" as sabrdimlsabmsabundle
 interface "list" as sabrdimlsabmsabundlelist
sabrdimlsabmsabundle -- sabrdimlsabmsabundlelist
}
}
}


hexagon "sabundleinstance.created" as sabundleinstancecreated
            sabrdimlsabm <-- sabundleinstancecreated

hexagon "sabundleinstance.deployed" as sabundleinstancedeployed
            sabrdimlsabm <-- sabundleinstancedeployed

hexagon "sabundleinstance.enabled" as sabundleinstanceenabled
            sabrdimlsabm <-- sabundleinstanceenabled









        rectangle "Manage SABR" as ManageSABR #ffffaa {
            ("Build SAB")/ as ApplicationDeveloperManageSABRBuildSAB
        }

    sabrdimlsabmsabundlebuild <-- ApplicationDeveloperManageSABRBuildSAB

        rectangle "Manage SABR" as ManageSABR #ffffaa {
            ("Create SABR")/ as ApplicationDeveloperManageSABRCreateSABR
        }

    sabrdimlsabmsabundlecreate <-- ApplicationDeveloperManageSABRCreateSABR

        rectangle "Manage SABR" as ManageSABR #ffffaa {
            ("Deploy SABR")/ as DevOpsEngineerManageSABRDeploySABR
        }

    sabrdimlsabmsabundledeploy <-- DevOpsEngineerManageSABRDeploySABR

        rectangle "Manage SABR" as ManageSABR #ffffaa {
            ("Deploy SABR two")/ as DevOpsEngineerManageSABRDeploySABR2
        }

    sabrdimlsabmsabundledeploy <-- DevOpsEngineerManageSABRDeploySABR2

        rectangle "Manage SABR" as ManageSABR #ffffaa {
            ("Deploy SABR three")/ as DevOpsEngineerManageSABRDeploySABR3
        }

    sabrdimlsabmsabundledeploy <-- DevOpsEngineerManageSABRDeploySABR3

        rectangle "Manage SABR" as ManageSABR #ffffaa {
            ("Deploy SABR four")/ as DevOpsEngineerManageSABRDeploySABR4
        }

    sabrdimlsabmsabundledeploy <-- DevOpsEngineerManageSABRDeploySABR4







@enduml
