@startuml


usecase "Update Capbility" as UpdateCapbility #yellow

Actor "DevOps Engineer" as DevOpsEngineer

DevOpsEngineer --> UpdateCapbility





usecase "0" as 0 #lightyellow

UpdateCapbility <-- 0 : extends







@enduml
