@startuml


usecase "Deploy Capability" as DeployCapability #yellow

Actor "DevOps Engineer" as DevOpsEngineer

DevOpsEngineer --> DeployCapability



usecase "DeployCapabilityRelease" as DeployCapabilityRelease #lightgrey

DeployCapability --> DeployCapabilityRelease



usecase "Manage Capabilities" as ManageCapabilities #lightyellow

DeployCapability <-- ManageCapabilities : extends







@enduml
