@startuml


usecase "Update Capability" as UpdateCapability #yellow

Actor "DevOps Engineer" as DevOpsEngineer

DevOpsEngineer --> UpdateCapability



usecase "AddaSABRtotheCapability" as AddaSABRtotheCapability #lightgrey

UpdateCapability --> AddaSABRtotheCapability

usecase "AddSABRstotheCapability" as AddSABRstotheCapability #lightgrey

UpdateCapability --> AddSABRstotheCapability

usecase "RemoveaSABRfromtheCapability" as RemoveaSABRfromtheCapability #lightgrey

UpdateCapability --> RemoveaSABRfromtheCapability

usecase "RemovemultipleSABRsfromtheCapability" as RemovemultipleSABRsfromtheCapability #lightgrey

UpdateCapability --> RemovemultipleSABRsfromtheCapability

usecase "UpdateConfigurationoftheCapability" as UpdateConfigurationoftheCapability #lightgrey

UpdateCapability --> UpdateConfigurationoftheCapability

usecase "UpdatePoliciesoftheCapability" as UpdatePoliciesoftheCapability #lightgrey

UpdateCapability --> UpdatePoliciesoftheCapability

usecase "UpdateSABRsoftheCapability" as UpdateSABRsoftheCapability #lightgrey

UpdateCapability --> UpdateSABRsoftheCapability



usecase "0" as 0 #lightyellow

UpdateCapability <-- 0 : extends







@enduml
