@startuml

actor "Actor"


entity EventBus

box Capability Manager #00aaff
    boundary cm #white
end box


box Capability Manager #00aaff
            participant capability
    end box


"Actor" -> cm: Add SABRs to the Capability

    cm -> "capability": create (name: myUpdateCap2,file: ./templates/capability.js)

    "capability" --/ EventBus: capability.create

    cm -> "capability manager": release (capability: UpdateCap2)

    "capability manager" --/ EventBus: capability.release

    cm -> "capability manager": deploy (capability: UpdateCap2)

    "capability manager" --/ EventBus: capability.deploy

    cm -> "capability manager": update (capability: UpdateCap2,file: ./templates/capabilityUpdateAddSABRs.js)

    "capability manager" --/ EventBus: capability.update

    cm -> "capability manager": release (capability: UpdateCap2)

    "capability manager" --/ EventBus: capability.release

    cm -> "capability manager": deploy (capability: UpdateCap2)

    "capability manager" --/ EventBus: capability.deploy



@enduml
