@startuml

actor "DevOpsEngineer"

actor "ApplicationDeveloper"


entity EventBus

box Capability Manager #00aaff
    boundary cm #white
end box


box Capability Manager #00aaff
            participant capability
    end box


"DevOpsEngineer" -> cm: Remove a SABR from the Capability

    cm -> "capability": create (name: UpdateCap3,file: ./templates/capability.js)

    "capability" --/ EventBus: capability.create

    cm -> "capability manager": release (capability: UpdateCap3)

    "capability manager" --/ EventBus: capability.release

    cm -> "capability manager": deploy (capability: UpdateCap3)

    "capability manager" --/ EventBus: capability.deploy

    cm -> "capability manager": update (capability: UpdateCap3,file: ./templates/capabilityRemoveSABR.js)

    "capability manager" --/ EventBus: capability.update

    cm -> "capability manager": release (capability: UpdateCap3)

    "capability manager" --/ EventBus: capability.release

    cm -> "capability manager": deploy (capability: UpdateCap3)

    "capability manager" --/ EventBus: capability.deploy


"ApplicationDeveloper" -> cm: Remove a SABR from the Capability

    cm -> "capability": create (name: UpdateCap3,file: ./templates/capability.js)

    "capability" --/ EventBus: capability.create

    cm -> "capability manager": release (capability: UpdateCap3)

    "capability manager" --/ EventBus: capability.release

    cm -> "capability manager": deploy (capability: UpdateCap3)

    "capability manager" --/ EventBus: capability.deploy

    cm -> "capability manager": update (capability: UpdateCap3,file: ./templates/capabilityRemoveSABR.js)

    "capability manager" --/ EventBus: capability.update

    cm -> "capability manager": release (capability: UpdateCap3)

    "capability manager" --/ EventBus: capability.release

    cm -> "capability manager": deploy (capability: UpdateCap3)

    "capability manager" --/ EventBus: capability.deploy



@enduml
