@startuml

class "SABundleInstance" as Model {
 string name
 string level

 deploy()
 
}

rectangle "SABundle" as SABundle #lightblue {
}

Model o--> "1" SABundle : parent


rectangle "InputStreamInstance" as InputStreamInstance #lightblue {
}

Model o--> "n" InputStreamInstance : inputs


rectangle "OutputStreamInstance" as OutputStreamInstance #lightblue {
}

Model o--> "n" OutputStreamInstance : outputs


rectangle "InputStreamInstance" as InputStreamInstance #lightblue {
}

Model o--> "1" InputStreamInstance : learningStream


rectangle "InputStreamInstance" as InputStreamInstance #lightblue {
}

Model o--> "1" InputStreamInstance : adminStream


rectangle "StackInstance" as StackInstance #lightblue {
}

Model o--> "n" StackInstance : stack


rectangle "AIModel" as AIModel #lightblue {
}

Model o--> "n" AIModel : aimodels


rectangle "DataTransformInstance" as DataTransformInstance #lightblue {
}

Model o--> "n" DataTransformInstance : transforms




    rectangle "CapabilityInstance" as CapabilityInstance #lightgreen {
    }
    
        CapabilityInstance   o--> "n" Model : "bundles"
    
    rectangle "DataChannelInstance" as DataChannelInstance #lightgreen {
    }
    
        DataChannelInstance   o--> "1" Model : "bundle"
    
    rectangle "DataStreamInstance" as DataStreamInstance #lightgreen {
    }
    
        DataStreamInstance   o--> "1" Model : "bundle"
    
    rectangle "SABundle" as SABundle #lightgreen {
    }
    
        SABundle   *--> "n" Model : "instances"
    
    rectangle "InputChannelInstance" as InputChannelInstance #lightgreen {
    }
    
        InputChannelInstance   o--> "1" Model : "bundle"
    
    rectangle "InputStreamInstance" as InputStreamInstance #lightgreen {
    }
    
        InputStreamInstance   o--> "1" Model : "bundle"
    
    rectangle "OutputChannelInstance" as OutputChannelInstance #lightgreen {
    }
    
        OutputChannelInstance   o--> "1" Model : "bundle"
    
    rectangle "OutputStreamInstance" as OutputStreamInstance #lightgreen {
    }
    
        OutputStreamInstance   o--> "1" Model : "bundle"
    

@enduml
