@startuml


usecase "Manage Policies" as ManagePolicies #yellow

Actor "IT Operations" as ITOperations

ITOperations --> ManagePolicies



usecase "CreatePolicy" as CreatePolicy #lightgrey

ManagePolicies --> CreatePolicy









@enduml
