@startuml


usecase "Manage SABR" as ManageSABR #yellow

Actor "DevOps Engineer" as DevOpsEngineer

DevOpsEngineer --> ManageSABR



usecase "BuildSAB" as BuildSAB #lightgrey

ManageSABR --> BuildSAB

usecase "CreateSABR" as CreateSABR #lightgrey

ManageSABR --> CreateSABR

usecase "DeploySABR" as DeploySABR #lightgrey

ManageSABR --> DeploySABR

usecase "DeploySABR2" as DeploySABR2 #lightgrey

ManageSABR --> DeploySABR2

usecase "DeploySABR3" as DeploySABR3 #lightgrey

ManageSABR --> DeploySABR3

usecase "DeploySABR4" as DeploySABR4 #lightgrey

ManageSABR --> DeploySABR4









@enduml
