@startuml

actor "ApplicationDeveloper"


entity EventBus

box Sentient Agent Bundle Manager #ffcc88
    boundary sabm #white
end box


box Sentient Agent Bundle Manager #ffcc88
            participant sabundle
    end box


"ApplicationDeveloper" -> sabm: Create SABR

    sabm -> "sabundle": create (name: mySABR1,file: ./templates/bundle1.js)

    "sabundle" --/ EventBus: sabundle.create

    sabm -> "sabundle": create (name: mySABR2,file: ./templates/bundle2.js)

    "sabundle" --/ EventBus: sabundle.create

    sabm -> "sabundle": create (name: mySABR3,file: ./templates/bundle3.js)

    "sabundle" --/ EventBus: sabundle.create

    sabm -> "sabundle": create (name: mySABR4,file: ./templates/bundle4.js)

    "sabundle" --/ EventBus: sabundle.create



@enduml
