@startuml


usecase "Provide Digital Assistance" as ProvideDigitalAssistance #yellow

Actor "Tactical Operator" as TacticalOperator

TacticalOperator --> ProvideDigitalAssistance







usecase "IntegrateLearning" as IntegrateLearning #lightyellow

ProvideDigitalAssistance --> IntegrateLearning : extends





@enduml
