@startuml



package "Sentient Agent Bundle Resources" #bbaaff {

    interface "Sentient Agent Bundle Resources" as i {
            /sabr/streampolicy activate()
            /sabr/streampolicy create()
            /sabr/streampolicy deactivate()
            /sabr/streampolicy update()
            /sabr/application/create()
            /sabr/bundle/build()
            /sabr/bundle/create()
            /sabr/capability/create()
            /sabr/environment/create()
            /sabr/pulsar/streams()
            /sabr/pulsar/topic()
            /sabr/pulsar/topics()
            /sabr/sabundle/build()
            /sabr/streampolicy/create()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Sentient Agent Bundle Resources" #bbaaff {
    
}



@enduml
