@startuml
left to right direction




state "sentient agent bundle resources" as pstatename #bbaaff {
    state "Custom Function" as sabrfunction {
    }
}

        state "streampolicy create" as streampolicycreate #bbaaff {
}


        state "application" as application #bbaaff {
state "create" as applicationcreate #bbaaff {
}
}


        state "bundle" as bundle #bbaaff {
state "build" as bundlebuild #bbaaff {
}
}


        state "bundle" as bundle #bbaaff {
state "create" as bundlecreate #bbaaff {
}
}


        state "capability" as capability #bbaaff {
state "create" as capabilitycreate #bbaaff {
}
}


        state "environment" as environment #bbaaff {
state "create" as environmentcreate #bbaaff {
}
}


        state "pulsar" as pulsar #bbaaff {
state "streams" as pulsarstreams #bbaaff {
}
}


        state "pulsar" as pulsar #bbaaff {
state "topic" as pulsartopic #bbaaff {
}
}


        state "pulsar" as pulsar #bbaaff {
state "topics" as pulsartopics #bbaaff {
}
}


        state "sabundle" as sabundle #bbaaff {
state "build" as sabundlebuild #bbaaff {
}
}


        state "streampolicy" as streampolicy #bbaaff {
state "create" as streampolicycreate #bbaaff {
}
}






@enduml
