@startuml
left to right direction




state "sentient agent bundle resources" as pstatename #bbaaff {
    state "Custom Function" as sabrfunction {
    }
}

        state "pulsar" as pulsar #bbaaff {
state "streams" as pulsarstreams #bbaaff {
}
}


        state "pulsar" as pulsar #bbaaff {
state "topic" as pulsartopic #bbaaff {
}
}


        state "pulsar" as pulsar #bbaaff {
state "topics" as pulsartopics #bbaaff {
}
}






@enduml
