@startuml
left to right direction



state "DataEngineer" as DataEngineer {
    state "Manage AI Model" as DataEngineerManageAIModel {
    }
}
state "sabr" as sabr #bbaaff {
state "aimodel" as sabraimodel #bbaaff {
state "list" as sabraimodellist #bbaaff {
}
}
}

DataEngineerManageAIModel --> sabraimodellist

state "DataScientist" as DataScientist {
    state "Manage AI Model" as DataScientistManageAIModel {
    }
}
state "sabr" as sabr #bbaaff {
state "aimodel" as sabraimodel #bbaaff {
state "list" as sabraimodellist #bbaaff {
}
}
}

DataScientistManageAIModel --> sabraimodellist

state "DataAnalyst" as DataAnalyst {
    state "Manage AI Model" as DataAnalystManageAIModel {
    }
}
state "sabr" as sabr #bbaaff {
state "aimodel" as sabraimodel #bbaaff {
state "list" as sabraimodellist #bbaaff {
}
}
}

DataAnalystManageAIModel --> sabraimodellist


 
state "DevOpsEngineer" as DevOpsEngineer {
    state "Manage Capabilities" as DevOpsEngineerManageCapabilities {
    }
}
state "sabr" as sabr #bbaaff {
state "capability" as sabrcapability #bbaaff {
state "list" as sabrcapabilitylist #bbaaff {
}
}
}

DevOpsEngineerManageCapabilities --> sabrcapabilitylist

state "ITOperations" as ITOperations {
    state "Manage Capabilities" as ITOperationsManageCapabilities {
    }
}
state "sabr" as sabr #bbaaff {
state "capability" as sabrcapability #bbaaff {
state "list" as sabrcapabilitylist #bbaaff {
}
}
}

ITOperationsManageCapabilities --> sabrcapabilitylist


 
state "ITOperations" as ITOperations {
    state "Manage Policies" as ITOperationsManagePolicies {
    }
}
state "sabr" as sabr #bbaaff {
state "policy" as sabrpolicy #bbaaff {
state "list" as sabrpolicylist #bbaaff {
}
}
}

ITOperationsManagePolicies --> sabrpolicylist


 
state "SecurityOperator" as SecurityOperator {
    state "Manage Security" as SecurityOperatorManageSecurity {
    }
}
state "sabr" as sabr #bbaaff {
state "security" as sabrsecurity #bbaaff {
state "list" as sabrsecuritylist #bbaaff {
}
}
}

SecurityOperatorManageSecurity --> sabrsecuritylist


 
state "TacticalOperator" as TacticalOperator {
    state "Provide Digital Assistance" as TacticalOperatorProvideDigitalAssistance {
    }
}
state "sabr" as sabr #bbaaff {
state "capability" as sabrcapability #bbaaff {
state "list" as sabrcapabilitylist #bbaaff {
}
}
}

TacticalOperatorProvideDigitalAssistance --> sabrcapabilitylist


 

@enduml
