@startuml

left to right direction
Actor "TacticalOperator" as TacticalOperator
Actor "AIDeveloper" as AIDeveloper
Actor "SoftwareDeveloper" as SoftwareDeveloper
Actor "DevOpsEngineer" as DevOpsEngineer


rectangle "Sentient Agent Bundle Resources" #bbaaff {
usecase "FindEnemyCombatant" as FindEnemyCombatant
    TacticalOperator --> FindEnemyCombatant
    usecase "ManageAIModel" as ManageAIModel
    AIDeveloper --> ManageAIModel
    usecase "ManageCapabilities" as ManageCapabilities
    SoftwareDeveloper --> ManageCapabilities
    usecase "ManageCapbilities" as ManageCapbilities
    DevOpsEngineer --> ManageCapbilities
    }


@enduml
