@startuml


actor "DataEngineer" as dataengineer

actor "DataScientist" as datascientist

actor "DataAnalyst" as analyst

actor "DevOpsEngineer" as devops

actor "ITOperations" as itops

actor "SecurityOperator" as secops

actor "TacticalOperator" as tacticaloperator




dataengineer -> "Sentient Agent Bundle Resources": Manage AI Model
"Sentient Agent Bundle Resources" -> bin: aimodel list
bin -> REST: aimodel/list

datascientist -> "Sentient Agent Bundle Resources": Manage AI Model
"Sentient Agent Bundle Resources" -> bin: aimodel list
bin -> REST: aimodel/list

analyst -> "Sentient Agent Bundle Resources": Manage AI Model
"Sentient Agent Bundle Resources" -> bin: aimodel list
bin -> REST: aimodel/list

devops -> "Sentient Agent Bundle Resources": Manage Capabilities
"Sentient Agent Bundle Resources" -> bin: capability list
bin -> REST: capability/list

devops -> "Sentient Agent Bundle Resources": Ships
"Sentient Agent Bundle Resources" -> bin: sabundle list
bin -> REST: sabundle/list

itops -> "Sentient Agent Bundle Resources": Manage Capabilities
"Sentient Agent Bundle Resources" -> bin: capability list
bin -> REST: capability/list

itops -> "Sentient Agent Bundle Resources": Manage Policies
"Sentient Agent Bundle Resources" -> bin: policy list
bin -> REST: policy/list

secops -> "Sentient Agent Bundle Resources": Manage Security
"Sentient Agent Bundle Resources" -> bin: security list
bin -> REST: security/list

tacticaloperator -> "Sentient Agent Bundle Resources": Provide Digital Assistance
"Sentient Agent Bundle Resources" -> bin: capability list
bin -> REST: capability/list

tacticaloperator -> "Sentient Agent Bundle Resources": Provide Mission Insight
"Sentient Agent Bundle Resources" -> bin: capability list
bin -> REST: capability/list



@enduml
