@startuml


package "Data Stream Manager" #ffcc88 {
    
        class DataStream {
        }
    
        class InputStreamInstance {
        }
    
        class OutputStreamInstance {
        }
    }

package "Security Aspect" #pink {
    }

package "Application Manager" #00aaff {
    
        class Application {
        }
    
        class Stack {
        }
    
        class StackInstance {
        }
    }

package "Learning Corpus" #00aaff {
    
        class AIModel {
        }
    }

package "Sentient Agent Bundle Manager" #ffcc88 {
    
        class DataTransform {
        }
    
        class SABundleInstance {
        }
    
        class SABundle {
        }
    
        class DataTransformInstance {
        }
    }


package "Sentient Agent Bundle Manager" #ffcc88 {

    interface "Sentient Agent Bundle Manager" as i {
            /sabr/diml/sabm/connect()
            /sabr/diml/sabm/bundle/createanddeploy()
            /sabr/diml/sabm/bundle/deploy()
            /sabr/diml/sabm/bundle/list()
            /sabr/diml/sabm/sabundle/create()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Sentient Agent Bundle Manager" #ffcc88 {
        class "DataTransform" {
                 string name
                 json fn
                    }
                DataTransform o--> "n" DataStream : inputs
                        DataTransform o--> "n" DataStream : outputs
            
    
    class "DataTransformInstance" {
                 string name
                 string version
                 json fn
                             run()
            }
                DataTransformInstance o--> "n" InputStreamInstance : inputs
                        DataTransformInstance o--> "n" OutputStreamInstance : outputs
            
    
    class "SABundle" {
                 string name
                 string version
                             create()
                     deploy()
                     toJScript()
            }
                SABundle o--> "n" DataStream : inputs
                        SABundle o--> "n" DataStream : outputs
                        SABundle o--> "1" DataStream : learningInput
                        SABundle o--> "1" DataStream : learningOutput
                        SABundle o--> "1" DataStream : adminStream
                        SABundle o--> "1" DataStream : admoutStream
                        SABundle o--> "n" DataTransform : transforms
                        SABundle o--> "n" Application : applications
                        SABundle o--> "n" Stack : stacks
                        SABundle o--> "n" AIModel : aimodels
                        SABundle *--> "n" SABundleInstance : instances
            
    
    class "SABundleInstance" {
                 string name
                 string level
                             deploy()
            }
                SABundleInstance o--> "1" SABundle : parent
                        SABundleInstance o--> "n" InputStreamInstance : inputs
                        SABundleInstance o--> "n" OutputStreamInstance : outputs
                        SABundleInstance o--> "1" InputStreamInstance : learningInput
                        SABundleInstance o--> "1" OutputStreamInstance : learningOutput
                        SABundleInstance o--> "1" InputStreamInstance : adminStream
                        SABundleInstance o--> "1" OutputStreamInstance : admoutStream
                        SABundleInstance o--> "n" StackInstance : stack
                        SABundleInstance o--> "n" AIModel : aimodels
                        SABundleInstance o--> "n" DataTransformInstance : transforms
            
    

}


    "Sentient Agent Bundle Manager" --> "Data Stream Manager"

    "Sentient Agent Bundle Manager" --> "Security Aspect"

    "Sentient Agent Bundle Manager" --> "Application Manager"

    "Sentient Agent Bundle Manager" --> "Learning Corpus"


@enduml
