@startuml


package "Data Stream Manager" #ffcc88 {
    
        class StreamPolicy {
        }
    
        class DataChannel {
        }
    
        class DataStreamInstance {
        }
    
        class DataStream {
        }
    
        class InputStreamInstance {
        }
    
        class OutputStreamInstance {
        }
    }

package "Security Aspect" #pink {
    
        class SecurityKey {
        }
    
        class SecureVault {
        }
    }

package "Application Manager" #00aaff {
    
        class Application {
        }
    
        class Stack {
        }
    
        class StackInstance {
        }
    }

package "Learning Corpus" #00aaff {
    
        class AIModel {
        }
    }

package "Sentient Agent Bundle Manager" #ffcc88 {
    
        class DataTransform {
        }
    
        class SABundle {
        }
    
        class SABundleInstance {
        }
    
        class SABundleBuild {
        }
    
        class DataTransformInstance {
        }
    }


package "Sentient Agent Bundle Manager" #ffcc88 {

    interface "Sentient Agent Bundle Manager" as i {
            /sabr/diml/sabm/connect()
            /sabr/diml/sabm/bundle/createanddeploy()
            /sabr/diml/sabm/bundle/deploy()
            /sabr/diml/sabm/policy/create()
            /sabr/diml/sabm/sabundle/build()
            /sabr/diml/sabm/sabundle/create()
            /sabr/diml/sabm/sabundle/deploy()
            /sabr/diml/sabm/sabundle/list()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Sentient Agent Bundle Manager" #ffcc88 {
        class "AdminDataStream" {
                 string name
                             create()
                     provision()
                     addKeysToStore()
                     build()
            }
                AdminDataStream o--> "n" StreamPolicy : policies
                        AdminDataStream *--> "n" DataChannel : channels
                        AdminDataStream *--> "n" DataStreamInstance : instances
                        AdminDataStream o--> "n" DataTransform : transforms
                        AdminDataStream o--> "n" SABundle : consumers
                        AdminDataStream o--> "n" SABundle : producers
                        AdminDataStream o--> "1" SecurityKey : encryptionKey
                        AdminDataStream o--> "1" SecurityKey : decryptionKey
            
    
        DataStream <|-- AdminDataStream
    
    class "AdminTransform" {
                 string name
                 json fn
                             create()
                     process()
            }
                AdminTransform o--> "n" DataStream : inputs
                        AdminTransform o--> "n" DataStream : outputs
            
    
        DataTransform <|-- AdminTransform
    
    class "DataTransform" {
                 string name
                 json fn
                    }
                DataTransform o--> "n" DataStream : inputs
                        DataTransform o--> "n" DataStream : outputs
            
    
    class "DataTransformInstance" {
                 string name
                 string version
                 json fn
                             run()
            }
                DataTransformInstance o--> "n" InputStreamInstance : inputs
                        DataTransformInstance o--> "n" OutputStreamInstance : outputs
            
    
    class "SABundle" {
                 string name
                 string version
                             build()
                     create()
                     deploy()
                     toJScript()
            }
                SABundle o--> "n" DataStream : inputs
                        SABundle o--> "n" DataStream : outputs
                        SABundle o--> "1" DataStream : learningStream
                        SABundle o--> "1" DataStream : adminStream
                        SABundle o--> "n" DataTransform : transforms
                        SABundle o--> "n" Application : applications
                        SABundle o--> "n" Stack : stacks
                        SABundle o--> "n" AIModel : aimodels
                        SABundle *--> "n" SABundleInstance : instances
                        SABundle *--> "1" SecureVault : secureVault
                        SABundle o--> "n" StreamPolicy : policies
                        SABundle o--> "n" SABundleBuild : builds
                        SABundle o--> "n" Image : images
            
    
    class "SABundleBuild" {
                 string name
                 string version
                 string encryptedData
                             encrypt()
            }
                SABundleBuild *--> "1" SecurityKey : encryptKey
                        SABundleBuild *--> "1" SecurityKey : decryptKey
                        SABundleBuild *--> "1" SecurityKey : iv
            
    
    class "SABundleInstance" {
                 string name
                 string level
                             deploy()
            }
                SABundleInstance o--> "1" SABundle : parent
                        SABundleInstance o--> "n" InputStreamInstance : inputs
                        SABundleInstance o--> "n" OutputStreamInstance : outputs
                        SABundleInstance o--> "1" InputStreamInstance : learningInStream
                        SABundleInstance o--> "1" InputStreamInstance : adminInStream
                        SABundleInstance o--> "1" OutputStreamInstance : learningOutStream
                        SABundleInstance o--> "1" OutputStreamInstance : adminOutStream
                        SABundleInstance o--> "n" StackInstance : stack
                        SABundleInstance o--> "n" AIModel : aimodels
                        SABundleInstance o--> "n" DataTransformInstance : transforms
            
    

}


    "Sentient Agent Bundle Manager" --> "Data Stream Manager"

    "Sentient Agent Bundle Manager" --> "Security Aspect"

    "Sentient Agent Bundle Manager" --> "Application Manager"

    "Sentient Agent Bundle Manager" --> "Learning Corpus"


@enduml
