@startuml

autonumber

actor ApplicationDeveloper as Dev
participant SABR
participant SABundle
participant SABBuild as SABB
participant Docker
participant SecurityAspect
participant EdgeSecurityControlServer as ESCS
actor SecurityEngineer
actor ITOps



SecurityEngineer -> ESCS : Generate Keys for Security Controller
SecurityEngineer -> SecurityAspect : Store Public Keys (LDAP)
ITOps -> Device : Provision with Key
Dev -> SABR : Build Bundle
SABR -> SABundle : build
SABundle -> SABundleBuild : create
autonumber 3.1
SABB -> FileSystem : create build directory
SABB -> Docker : build images
SABB -> SecurityAspect : Get Public Key For Device Types
SABB -> SecurityAspect : generate random key
SABB -> SecurityAspect : Encrypt Bundle with Random Key
SABB -> SecurityAspect : Encrypt Random Key with Public Key
SABB -> ESCS : Store Bundle

'Mutually Authenticated SSL for Streams (Mutual TLS)
'Authentication to the Stream
'Authentication protocols to do this.
@enduml
