@startuml
left to right direction



state "DevOpsEngineer" as DevOpsEngineer {
    state "Manage SABR" as DevOpsEngineerManageSABR {
    }
}
state "sabr" as sabr #ffcc88 {
state "diml" as sabrdiml #ffcc88 {
state "sabm" as sabrdimlsabm #ffcc88 {
state "sabundle" as sabrdimlsabmsabundle #ffcc88 {
state "list" as sabrdimlsabmsabundlelist #ffcc88 {
}
}
}
}
}

DevOpsEngineerManageSABR --> sabrdimlsabmsabundlelist


    state "ApplicationDeveloper" as ApplicationDeveloper {
        state "Manage SABR" as ApplicationDeveloperManageSABR {
            state "Create SABR" as ApplicationDeveloperManageSABRCreateSABR {
            }
        }
    }
    
    ApplicationDeveloperManageSABRCreateSABR --> Null
    
 
    state "DevOpsEngineer" as DevOpsEngineer {
        state "Manage SABR" as DevOpsEngineerManageSABR {
            state "Deploy SABR" as DevOpsEngineerManageSABRDeploySABR {
            }
        }
    }
    
    DevOpsEngineerManageSABRDeploySABR --> Null
    
 
    state "DevOpsEngineer" as DevOpsEngineer {
        state "Manage SABR" as DevOpsEngineerManageSABR {
            state "Deploy SABR two" as DevOpsEngineerManageSABRDeploySABR2 {
            }
        }
    }
    
    DevOpsEngineerManageSABRDeploySABR2 --> Null
    
 
    state "DevOpsEngineer" as DevOpsEngineer {
        state "Manage SABR" as DevOpsEngineerManageSABR {
            state "Deploy SABR three" as DevOpsEngineerManageSABRDeploySABR3 {
            }
        }
    }
    
    DevOpsEngineerManageSABRDeploySABR3 --> Null
    
 
    state "DevOpsEngineer" as DevOpsEngineer {
        state "Manage SABR" as DevOpsEngineerManageSABR {
            state "Deploy SABR four" as DevOpsEngineerManageSABRDeploySABR4 {
            }
        }
    }
    
    DevOpsEngineerManageSABRDeploySABR4 --> Null
    
 
 

@enduml
