@startuml
partition "IdentityAspect" #ffbbbb {
(*) --> "Attest Device Process"
}
partition "IdentityAspect" #ffbbbb {
"Attest Device Process" --> if "Device is Trusted" then
}
partition "SecurityAspect" pink {
else
--> [Yes] "Provision Edge Security Controller"
}
partition "SoftwareDefinedInfrastructure" lightyellow {
else
--> [No] "Reject the Device"
}
partition "None" #dddddd {
"Provision Edge Security Controller" --> "Store SABR Private Keys"
}

@enduml
