@startuml
partition "ApplicationDeveloper" #ffffcc {
(*) --> ===F1===
}

partition "SentientAgentBundleManager" #ffcc88 {
===F1=== --> "Build SABR Process"
}

partition "SecurityAspect" pink {
===F1=== --> "Security Key Generation Process"
}
partition "ServiceOrchestrator" #aaffaa {
"Build SABR Process" --> "Deploy SABR Build Process"
}
partition "SoftwareDefinedInfrastructure" lightyellow {
"Security Key Generation Process" --> "Device Provision Process"
}
partition "ServiceOrchestrator" #aaffaa {
"Device Provision Process" --> "Deploy SABR Build Process"
}
partition "SentientAgentBundleManager" #ffcc88 {
"Deploy SABR Build Process" --> "DeploySABR"
}

@enduml
