@startuml

left to right direction
Actor "ApplicationDeveloper" as ApplicationDeveloper
Actor "DevOpsEngineer" as DevOpsEngineer
Actor "ApplicationDeveloper" as ApplicationDeveloper


rectangle "Application Manager" #00aaff {
usecase "IntegrateLearning" as IntegrateLearning
    ApplicationDeveloper --> IntegrateLearning
    usecase "ManageApplication" as ManageApplication
    DevOpsEngineer --> ManageApplication
    ApplicationDeveloper --> ManageApplication
    }


@enduml
