@startuml

left to right direction


Actor "Data Analyst" as DataAnalyst


rectangle "Sentient Agent Bundle Resources" as sabr #bbaaff {
        usecase "Manage AI Model" as ManageAIModel
    DataAnalyst --> ManageAIModel

}


@enduml
