@startuml

left to right direction


boundary parent #black


entity children #blue




package "sabr_diml" #ffcc88 {
    queue parentnet #black [
            <b><color:white>parent</color></b>
    ]
    
    parentnet -[#black]- parent
    
    queue childrennet #blue [
            <b><color:white>children</color></b>
    ]
    
    childrennet -[#blue]- children
    
    queue siblingsnet #red [
            <b><color:white>siblings</color></b>
    ]
    

node "dsm" as dsmService
node "sabm" as sabmService


        artifact "sabr_diml_dsm" as sabr_diml_dsmimage
    
        artifact "sabr_diml_sabm" as sabr_diml_sabmimage
    
}

dsmService -[#blue]- childrennet

sabmService -[#blue]- childrennet
dsmService .... sabr_diml_dsmimage
sabmService .... sabr_diml_sabmimage


@enduml
