@startuml



state StackInstance #00aaff {

    state Init #00aaff {
    }

    state Deploying #00aaff {
    }

    state Deployed #00aaff {
    }

    state Provisioning #00aaff {
    }

    state Running #00aaff {
    }

    state Killing #00aaff {
    }

    state Failed #00aaff {
    }

    state Completed #00aaff {
    }

    state Killed #00aaff {
    }

}


Init --> Deploying : create




@enduml
