@startuml

class "Capability" as Model {
 string name

 build()
 create()
 deploy()
 release()
 test()
 
}

rectangle "ChannelCreationPolicy" as ChannelCreationPolicy #lightblue {
}

Model o--> "n" ChannelCreationPolicy : policies


rectangle "SABundle" as SABundle #lightblue {
}

Model o--> "n" SABundle : bundles


rectangle "CapabilityInstance" as CapabilityInstance #lightblue {
}

Model *--> "n" CapabilityInstance : instances




    rectangle "CapabilityInstance" as CapabilityInstance #lightgreen {
    }
    
        CapabilityInstance   o--> "1" Model : "owner"
    

@enduml
