@startuml



state Capability #00aaff {

    state Init #00aaff {
    }

    state Created #00aaff {
    }

    state Building #00aaff {
    }

    state Built #00aaff {
    }

    state Testing #00aaff {
    }

    state Tested #00aaff {
    }

    state Released #00aaff {
    }

    state Failed #00aaff {
    }




Init -[#black]--> Created : create

Created -[#black]--> Building : build

state builtCondition <<choice>>
Building -[#black]--> builtCondition : built

builtCondition -[#black]--> Built: [Custom]

builtCondition -[#black]--> Failed: [Custom]

Built -[#black]--> Testing : test

Testing -[#black]--> Tested : testSuccess

Tested -[#black]--> Released : release

Released -[#black]--> Released : deploy

}


@enduml
