@startuml

left to right direction


queue external #black [
    <b><color:white>external</color></b>
]
    
interface 6650
6650 -- external
    
interface 8081
8081 -- external
    





package "_sabm" #ffcc88 {
    queue childrennet #black [
            <b><color:white>children</color></b>
    ]
    

node "pulsar" as pulsarService


        artifact "apachepulsar/pulsar-all:latest" as apachepulsar/pulsar-alllatestimage
    
}

pulsarService -[#black]- childrennet
pulsarService .... apachepulsar/pulsar-alllatestimage


@enduml
