@startuml

class "JWT" as Model {
 string attr1

 
}

rectangle "ModelName" as ModelName #lightblue {
}

Model o--> "1" ModelName : assoc1




    rectangle "WorkingEnclave" as WorkingEnclave #lightgreen {
    }
    
        WorkingEnclave   o--> "1" Model : "token"
    

@enduml
