docker run -d --network sabr_network aisship1000
docker run -d --network sabr_network aisship2000
docker run -d --network sabr_network aisship3000
docker run -d --network sabr_network aisship4000
docker run -d --network sabr_network aisship5000
docker run -d --network sabr_network aisship6000
docker run -d --network sabr_network aisship7000
docker run -d --network sabr_network aisship8000
docker run -d --network sabr_network aisship9000
docker run -d --network sabr_network aisship10000
docker run -d --network sabr_network aisship11000
docker run -d --network sabr_network aisship12000
docker run -d --network sabr_network aisship13000
docker run -d --network sabr_network aisship14000
docker run -d --network sabr_network aisship15000
docker run -d --network sabr_network aisship16000
docker run -d --network sabr_network aisship17000
docker run -d --network sabr_network aisship18000
docker run -d --network sabr_network aisship19000
docker run -d --network sabr_network aisship20000
docker run -d --network sabr_network aisship21000
docker run -d --network sabr_network aisship22000
