@startuml
  interface CLI
  interface Web
  interface WebSocket
package "Capability Manager" #00aaff {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component " sabr aml cm" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\n" as sabr_aml_cm_container
      REST --> sabr_aml_cm_container

  
    file "web" as web_container
    REST --> web_container
    socket ---> web_container
  
  }
  folder images #ffffff {
    collections "sabr_aml_cm" as sabr_aml_cmimage
    artifact "ailtire:swarm" as ailtireswarm
    sabr_aml_cmimage <|-- ailtireswarm
    sabr_aml_cm_container --> sabr_aml_cmimage

  
      artifact "sabr_aml_cm_web" as sabr_aml_cm_web
      web_container --> sabr_aml_cm_web
    
  }
}
CLI " sabr aml cm" -- binName
Web "/sabr/aml/cm" - REST
WebSocket ".sabr.aml.cm" -- socket

@enduml
