@startuml

left to right direction


boundary parent #black


entity children #blue




package "sabr_cpl" #bbbbbb {
    queue parentnet #black [
            <b><color:white>parent</color></b>
    ]

    parentnet -[#black]- parent

    queue childrennet #blue [
            <b><color:white>children</color></b>
    ]

    childrennet -[#blue]- children

    queue siblingsnet #red [
            <b><color:white>siblings</color></b>
    ]


node "cpl_web" as cpl_webService


        artifact "sabr_cpl_web" as sabr_cpl_webimage

}

cpl_webService -[#red]- siblingsnet
cpl_webService .... sabr_cpl_webimage


@enduml
