remote_theme: pmarsceill/just-the-docs
title: Sentient Agent Bundle Resources Architecture v0.0.1
description: SABR is a system architecture that enables data transformation through deployment and managment AI algorightms in the data center, cloud and at the semi-connected edge.
google_analytics: G-SDCPXLJ9YG
