remote_theme: pmarsceill/just-the-docs
title: SABR v0.1.4
description: SABR is a system architecture that enables data transformation through deployment and management of AI algorithms in the data center, cloud and at the semi-connected edge.
google_analytics: G-SDCPXLJ9YG
