version: "3.7"
services:
  registry:
    image: sabr_registry
    ports:
      - "5000:5000"
    networks:
      - children
  sabr_builder:
    image: sabr_builder
    environment:
      - "SABR_REGISTRY=registry"
    networks

      - children
  sabr2:
    image: sabr
    environment:
      - "PULSAR_ADMIN=tasks.pulsar:8080"
      - "PULSAR_HOST=tasks.pulsar:6650"
      - "SABR_STREAM=./streams2.js"
      - "SABR_NAME=sabr2"
    networks:
      - children
  sabr3:
    image: sabr
    environment:
      - "PULSAR_ADMIN=tasks.pulsar:8080"
      - "PULSAR_HOST=tasks.pulsar:6650"
      - "SABR_STREAM=./streams3.js"
      - "SABR_NAME=sabr3"
    networks:
      - children
networks:
  children:
    driver: overlay
