@startuml

actor "DevOpsEngineer"


entity EventBus

box Application Manager #00aaff
    boundary am #white
end box


box Application Manager #00aaff
            participant application
    end box


"DevOpsEngineer" -> am: Update Application

    am -> "application": update (name: hello,file: ./templates/world.yml)

    "application" --/ EventBus: application.update



@enduml
