@startuml

class "SecureVault" as Model {
 string name

 encrypt()
 
}

rectangle "Seed" as Seed #lightblue {
}

Model *--> "1" Seed : seed


rectangle "WorkingEnclave" as WorkingEnclave #lightblue {
}

Model *--> "1" WorkingEnclave : enclave


rectangle "EncryptedVault" as EncryptedVault #lightblue {
}

Model *--> "1" EncryptedVault : vault




    rectangle "SABundle" as SABundle #lightgreen {
    }
    
        SABundle   *--> "1" Model : "secureVault"
    

@enduml
