@startuml

class "SecureVault" as Model {
 string name

 encrypt()
 
}

rectangle "SecurityKey" as SecurityKey #lightblue {
}

Model *--> "1" SecurityKey : encryptKey


rectangle "SecurityKey" as SecurityKey #lightblue {
}

Model *--> "1" SecurityKey : decryptKey


rectangle "KeyStore" as KeyStore #lightblue {
}

Model *--> "1" KeyStore : store




    rectangle "SABundle" as SABundle #lightgreen {
    }
    
        SABundle   *--> "1" Model : "secureVault"
    

@enduml
