@startuml

class "DataChannel" as Model {
 string name
 string direction

 build()

}

rectangle "Service" as Service #lightblue {
}

Model o--> "1" Service : transformService


rectangle "StreamPolicy" as StreamPolicy #lightblue {
}

Model o--> "n" StreamPolicy : policy


rectangle "DataChannelInstance" as DataChannelInstance #lightblue {
}

Model o--> "n" DataChannelInstance : instances


rectangle "DataStream" as DataStream #lightblue {
}

Model o--> "1" DataStream : stream


rectangle "SecurityKey" as SecurityKey #lightblue {
}

Model o--> "1" SecurityKey : encryptionKey


rectangle "SecurityKey" as SecurityKey #lightblue {
}

Model o--> "1" SecurityKey : decryptionKey




    rectangle "DataChannelInstance" as DataChannelInstance #lightgreen {
    }

        DataChannelInstance   o--> "1" Model : "design"

    rectangle "DataStream" as DataStream #lightgreen {
    }

        DataStream   *--> "n" Model : "channels"

    rectangle "InputChannelInstance" as InputChannelInstance #lightgreen {
    }

        InputChannelInstance   o--> "1" Model : "design"

    rectangle "OutputChannelInstance" as OutputChannelInstance #lightgreen {
    }

        OutputChannelInstance   o--> "1" Model : "design"

    rectangle "StreamPolicy" as StreamPolicy #lightgreen {
    }

        StreamPolicy   o--> "n" Model : "channels"

    rectangle "AdminDataStream" as AdminDataStream #lightgreen {
    }

        AdminDataStream   *--> "n" Model : "channels"


@enduml
