@startuml

class "OutputChannelInstance" as Model {
 ref producer
 ref queue
 string producerName
 string name
 string direction
 string message

 create()
 deploy()
 send()
 failed()
 
}

rectangle "DataChannel" as DataChannel #lightblue {
}

Model o--> "1" DataChannel : design


rectangle "DataStreamInstance" as DataStreamInstance #lightblue {
}

Model o--> "1" DataStreamInstance : stream


rectangle "ServiceInstance" as ServiceInstance #lightblue {
}

Model o--> "n" ServiceInstance : transformInstance


rectangle "SABundleInstance" as SABundleInstance #lightblue {
}

Model o--> "1" SABundleInstance : bundle





@enduml
