@startuml


package "Security Aspect" #pink {
    
        class SecurityKey {
        }
    
        class KeyStore {
        }
    }


package "Security Aspect" #pink {

    interface "Security Aspect" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Security Aspect" #pink {
        class "KeyStore" {
                 string name
                    }
                KeyStore o--> "n" SecurityKey : keys
            
    
    class "SecureVault" {
                 string name
                             encrypt()
            }
                SecureVault *--> "1" SecurityKey : encryptKey
                        SecureVault *--> "1" SecurityKey : decryptKey
                        SecureVault *--> "1" KeyStore : store
            
    
    class "SecurityKey" {
                 string name
                 string value
                    }
    
    

}



@enduml
