@startuml


package "Security Aspect" #pink {

}


package "Security Aspect" #pink {

    interface "Security Aspect" as i {
    
            /sabr/sa/securitymanager/authenticate()
            /sabr/sa/securitymanager/generatestreamkeys()
            /sabr/sa/securitymanager/getbootstrapkey()
            /sabr/sa/securitymanager/getregistrationcreds()
            /sabr/sa/securitymanager/getstreamkeys()
            /sabr/sa/securitymanager/provisionentity()
            /sabr/sa/securitymanager/registerentity()
            /sabr/sa/securitymanager/requestkeys()
            /sabr/sa/securitymanager/validate()
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Security Aspect" #pink {


rectangle "Edge Security Controller" #white {
}

rectangle "Key Manager" #white {
}

}



@enduml
