@startuml


package "Software Defined Infrastructure" #lightyellow {
    }

package "Distributed Information Management Layer" #ffcc88 {
    }


package "Service Management Layer" #lightgreen {

    interface "Service Management Layer" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Service Management Layer" #lightgreen {
    
}


    "Service Management Layer" --> "Software Defined Infrastructure"

    "Service Management Layer" --> "Distributed Information Management Layer"


@enduml
