@startuml
left to right direction


state "sa" as sa #pink {
state "esc" as saesc #lightblue {
}
}


state "saesc" as pstatename #lightblue {
    state "Custom Function" as escfunction {
    }
}

        state "sa" as sa #pink {
state "esc" as saesc #lightblue {
state "bundle" as saescbundle #lightblue {
state "deploy" as saescbundledeploy #lightblue {
}
}
}
}


        state "sa" as sa #pink {
state "esc" as saesc #lightblue {
state "key" as saesckey #lightblue {
state "store" as saesckeystore #lightblue {
}
}
}
}






@enduml
