@startuml

class "DataChannelInstance" as Model {
 string name
 string direction
 string message

 create()
 failed()
 
}

rectangle "DataChannel" as DataChannel #lightblue {
}

Model o--> "1" DataChannel : design


rectangle "DataStreamInstance" as DataStreamInstance #lightblue {
}

Model o--> "1" DataStreamInstance : stream


rectangle "ServiceInstance" as ServiceInstance #lightblue {
}

Model o--> "n" ServiceInstance : transformInstance


rectangle "SABundleInstance" as SABundleInstance #lightblue {
}

Model o--> "1" SABundleInstance : bundle




    rectangle "DataChannel" as DataChannel #lightgreen {
    }
    
        DataChannel   o--> "n" Model : "instances"
    
    rectangle "DataStreamInstance" as DataStreamInstance #lightgreen {
    }
    
        DataStreamInstance   *--> "n" Model : "channels"
    
    rectangle "DataStreamInstance" as DataStreamInstance #lightgreen {
    }
    
        DataStreamInstance   o--> "n" Model : "policies"
    
    rectangle "InputStreamInstance" as InputStreamInstance #lightgreen {
    }
    
        InputStreamInstance   *--> "n" Model : "channels"
    
    rectangle "InputStreamInstance" as InputStreamInstance #lightgreen {
    }
    
        InputStreamInstance   o--> "n" Model : "policies"
    
    rectangle "OutputStreamInstance" as OutputStreamInstance #lightgreen {
    }
    
        OutputStreamInstance   *--> "n" Model : "channels"
    
    rectangle "OutputStreamInstance" as OutputStreamInstance #lightgreen {
    }
    
        OutputStreamInstance   o--> "n" Model : "policies"
    

@enduml
