@startuml


package "Distributed Information Management Layer" #ffcc88 {

}

package "Service Management Layer" #lightgreen {

}

package "Security Aspect" #pink {

}

package "Identity Aspect" #pink {

}


package "Application Management Layer" #00aaff {

    interface "Application Management Layer" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Application Management Layer" #00aaff {


rectangle "Application Manager" #white {
}

rectangle "Capability Manager" #white {
}

rectangle "Learning Corpus" #white {
}

    "Application Manager" --> "Service Orchestrator"
    
    "Capability Manager" --> "Sentient Agent Bundle Manager"
    
    "Capability Manager" --> "Application Manager"
    
}


    "Application Management Layer" --> "Distributed Information Management Layer"

    "Application Management Layer" --> "Service Management Layer"

    "Application Management Layer" --> "Security Aspect"

    "Application Management Layer" --> "Identity Aspect"


@enduml
