@startuml


package "Distributed Information Management Layer" #ffcc88 {

}

package "Service Management Layer" #lightgreen {

}

package "Security Aspect" #pink {

}

package "Identity Aspect" #ffbbbb {

}


package "Application Management Layer" #00aaff {

    interface "Application Management Layer" as i {
    
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Application Management Layer" #00aaff {


rectangle "Application Manager" #white {
}

rectangle "Capability Manager" #white {
}

rectangle "DevSecOpsManager" #white {
}

rectangle "Learning Corpus" #white {
}

    "Application Manager" --> "Service Orchestrator"
    
    "Capability Manager" --> "Sentient Agent Bundle Manager"
    
    "Capability Manager" --> "Application Manager"
    
}


    "Distributed Information Management Layer" <-- "Application Management Layer"

    "Service Management Layer" <-- "Application Management Layer"

    "Security Aspect" <-- "Application Management Layer"

    "Identity Aspect" <-- "Application Management Layer"


@enduml
