@startuml


package "Sentient Agent Bundle Manager" #ffcc88 {
    
        class SABundle {
        }
    
        class SABundleInstance {
        }
    }

package "Application Manager" #00aaff {
    }

package "Data Stream Manager" #ffcc88 {
    
        class ChannelCreationPolicy {
        }
    }

package "Capability Manager" #00aaff {
    
        class CapabilityInstance {
        }
    
        class Capability {
        }
    }

package "Service Orchestrator" #aaffaa {
    
        class Provisioner {
        }
    }


package "Capability Manager" #00aaff {

    interface "Capability Manager" as i {
            /sabr/aml/cm/capability/build()
            /sabr/aml/cm/capability/create()
            /sabr/aml/cm/capability/deploy()
            /sabr/aml/cm/capability/list()
            /sabr/aml/cm/capability/release()
            /sabr/aml/cm/capability/remove()
            /sabr/aml/cm/capability/test()
            /sabr/aml/cm/capability/update()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Capability Manager" #00aaff {
        class "Capability" {
                 string name
                             build()
                     create()
                     deploy()
                     release()
                     test()
            }
                Capability o--> "n" ChannelCreationPolicy : policies
                        Capability o--> "n" SABundle : bundles
                        Capability *--> "n" CapabilityInstance : instances
            
    
    class "CapabilityInstance" {
                 string name
                             deploy()
                     kill()
                     update()
            }
                CapabilityInstance o--> "n" SABundleInstance : bundles
                        CapabilityInstance o--> "1" Capability : owner
                        CapabilityInstance o--> "1" Provisioner : provisioner
            
    

}


    "Capability Manager" --> "Sentient Agent Bundle Manager"

    "Capability Manager" --> "Application Manager"


@enduml
