@startuml
left to right direction


state "aml" as aml #00aaff {
state "cm" as amlcm #00aaff {
}
}


state "amlcm" as pstatename #00aaff {
    state "Custom Function" as cmfunction {
    }
}

        state "aml" as aml #00aaff {
state "cm" as amlcm #00aaff {
state "capability" as amlcmcapability #00aaff {
state "build" as amlcmcapabilitybuild #00aaff {
}
}
}
}


        state "aml" as aml #00aaff {
state "cm" as amlcm #00aaff {
state "capability" as amlcmcapability #00aaff {
state "create" as amlcmcapabilitycreate #00aaff {
}
}
}
}


        state "aml" as aml #00aaff {
state "cm" as amlcm #00aaff {
state "capability" as amlcmcapability #00aaff {
state "deploy" as amlcmcapabilitydeploy #00aaff {
}
}
}
}


        state "aml" as aml #00aaff {
state "cm" as amlcm #00aaff {
state "capability" as amlcmcapability #00aaff {
state "list" as amlcmcapabilitylist #00aaff {
}
}
}
}


        state "aml" as aml #00aaff {
state "cm" as amlcm #00aaff {
state "capability" as amlcmcapability #00aaff {
state "release" as amlcmcapabilityrelease #00aaff {
}
}
}
}


        state "aml" as aml #00aaff {
state "cm" as amlcm #00aaff {
state "capability" as amlcmcapability #00aaff {
state "remove" as amlcmcapabilityremove #00aaff {
}
}
}
}


        state "aml" as aml #00aaff {
state "cm" as amlcm #00aaff {
state "capability" as amlcmcapability #00aaff {
state "test" as amlcmcapabilitytest #00aaff {
}
}
}
}


        state "aml" as aml #00aaff {
state "cm" as amlcm #00aaff {
state "capability" as amlcmcapability #00aaff {
state "update" as amlcmcapabilityupdate #00aaff {
}
}
}
}






@enduml
