@startuml
left to right direction



state "DevOpsEngineer" as DevOpsEngineer {
    state "Deploy Capability" as DevOpsEngineerDeployCapability {
    }
}
state "sabr" as sabr #00aaff {
state "aml" as sabraml #00aaff {
state "cm" as sabramlcm #00aaff {
state "capability" as sabramlcmcapability #00aaff {
state "deploy" as sabramlcmcapabilitydeploy #00aaff {
}
}
}
}
}

DevOpsEngineerDeployCapability --> sabramlcmcapabilitydeploy


    state "DevOpsEngineer" as DevOpsEngineer {
        state "Deploy Capability" as DevOpsEngineerDeployCapability {
            state "Deploy Capability Release" as DevOpsEngineerDeployCapabilityDeployCapabilityRelease {
            }
        }
    }
    
    DevOpsEngineerDeployCapabilityDeployCapabilityRelease --> Null
    
 
 
state "Application Developer" as ApplicationDeveloper {
    state "Develop Capability" as ApplicationDeveloperDevelopCapability {
    }
}
state "sabr" as sabr #00aaff {
state "aml" as sabraml #00aaff {
state "cm" as sabramlcm #00aaff {
state "capability" as sabramlcmcapability #00aaff {
state "list" as sabramlcmcapabilitylist #00aaff {
}
}
}
}
}

ApplicationDeveloperDevelopCapability --> sabramlcmcapabilitylist


    state "DevOpsEngineer" as DevOpsEngineer {
        state "Develop Capability" as DevOpsEngineerDevelopCapability {
            state "Build Capability" as DevOpsEngineerDevelopCapabilityBuildCapability {
            }
        }
    }
    
    DevOpsEngineerDevelopCapabilityBuildCapability --> Null
    
 
    state "DevOpsEngineer" as DevOpsEngineer {
        state "Develop Capability" as DevOpsEngineerDevelopCapability {
            state "Create Capability" as DevOpsEngineerDevelopCapabilityCreateCapability {
            }
        }
    }
    
    DevOpsEngineerDevelopCapabilityCreateCapability --> Null
    
 
    state "DevOpsEngineer" as DevOpsEngineer {
        state "Develop Capability" as DevOpsEngineerDevelopCapability {
            state "Release Capability" as DevOpsEngineerDevelopCapabilityReleaseCapability {
            }
        }
    }
    
    DevOpsEngineerDevelopCapabilityReleaseCapability --> Null
    
 
    state "DevOpsEngineer" as DevOpsEngineer {
        state "Develop Capability" as DevOpsEngineerDevelopCapability {
            state "Test Capability" as DevOpsEngineerDevelopCapabilityTestCapability {
            }
        }
    }
    
    DevOpsEngineerDevelopCapabilityTestCapability --> Null
    
 
 
state "DevOpsEngineer" as DevOpsEngineer {
    state "Remove Capability" as DevOpsEngineerRemoveCapability {
    }
}
state "sabr" as sabr #00aaff {
state "aml" as sabraml #00aaff {
state "cm" as sabramlcm #00aaff {
state "capability" as sabramlcmcapability #00aaff {
state "remove" as sabramlcmcapabilityremove #00aaff {
}
}
}
}
}

DevOpsEngineerRemoveCapability --> sabramlcmcapabilityremove


 
state "DevOpsEngineer" as DevOpsEngineer {
    state "Update Capability" as DevOpsEngineerUpdateCapability {
    }
}
state "sabr" as sabr #00aaff {
state "aml" as sabraml #00aaff {
state "cm" as sabramlcm #00aaff {
state "capability" as sabramlcmcapability #00aaff {
state "update" as sabramlcmcapabilityupdate #00aaff {
}
}
}
}
}

DevOpsEngineerUpdateCapability --> sabramlcmcapabilityupdate


    state "DevOpsEngineer" as DevOpsEngineer {
        state "Update Capability" as DevOpsEngineerUpdateCapability {
            state "Add a SABR to the Capability" as DevOpsEngineerUpdateCapabilityAddaSABRtotheCapability {
            }
        }
    }
    
    DevOpsEngineerUpdateCapabilityAddaSABRtotheCapability --> Null
    
 
    state "Actor" as Actor {
        state "Update Capability" as ActorUpdateCapability {
            state "Add SABRs to the Capability" as ActorUpdateCapabilityAddSABRstotheCapability {
            }
        }
    }
    
    ActorUpdateCapabilityAddSABRstotheCapability --> Null
    
 
    state "DevOpsEngineer" as DevOpsEngineer {
        state "Update Capability" as DevOpsEngineerUpdateCapability {
            state "Remove a SABR from the Capability" as DevOpsEngineerUpdateCapabilityRemoveaSABRfromtheCapability {
            }
        }
    }
    
    DevOpsEngineerUpdateCapabilityRemoveaSABRfromtheCapability --> Null
    
    state "ApplicationDeveloper" as ApplicationDeveloper {
        state "Update Capability" as ApplicationDeveloperUpdateCapability {
            state "Remove a SABR from the Capability" as ApplicationDeveloperUpdateCapabilityRemoveaSABRfromtheCapability {
            }
        }
    }
    
    ApplicationDeveloperUpdateCapabilityRemoveaSABRfromtheCapability --> Null
    
 
    state "DevOpsEngineer" as DevOpsEngineer {
        state "Update Capability" as DevOpsEngineerUpdateCapability {
            state "Remove multiple SABRs from the Capability" as DevOpsEngineerUpdateCapabilityRemovemultipleSABRsfromtheCapability {
            }
        }
    }
    
    DevOpsEngineerUpdateCapabilityRemovemultipleSABRsfromtheCapability --> Null
    
 
    state "DevOpsEngineer" as DevOpsEngineer {
        state "Update Capability" as DevOpsEngineerUpdateCapability {
            state "Update Configuration of the Capability" as DevOpsEngineerUpdateCapabilityUpdateConfigurationoftheCapability {
            }
        }
    }
    
    DevOpsEngineerUpdateCapabilityUpdateConfigurationoftheCapability --> Null
    
 
    state "DevOpsEngineer" as DevOpsEngineer {
        state "Update Capability" as DevOpsEngineerUpdateCapability {
            state "Update Policies of the Capability" as DevOpsEngineerUpdateCapabilityUpdatePoliciesoftheCapability {
            }
        }
    }
    
    DevOpsEngineerUpdateCapabilityUpdatePoliciesoftheCapability --> Null
    
 
    state "DevOpsEngineer" as DevOpsEngineer {
        state "Update Capability" as DevOpsEngineerUpdateCapability {
            state "Update SABRs of the Capability" as DevOpsEngineerUpdateCapabilityUpdateSABRsoftheCapability {
            }
        }
    }
    
    DevOpsEngineerUpdateCapabilityUpdateSABRsoftheCapability --> Null
    
 
 

@enduml
