@startuml

left to right direction
Actor "DevOpsEngineer" as DevOpsEngineer
Actor "Application Developer" as ApplicationDeveloper
Actor "DevOpsEngineer" as DevOpsEngineer
Actor "DevOpsEngineer" as DevOpsEngineer


rectangle "Capability Manager" #00aaff {
usecase "DeployCapability" as DeployCapability
    DevOpsEngineer --> DeployCapability
    usecase "DevelopCapability" as DevelopCapability
    ApplicationDeveloper --> DevelopCapability
    usecase "RemoveCapability" as RemoveCapability
    DevOpsEngineer --> RemoveCapability
    usecase "UpdateCapability" as UpdateCapability
    DevOpsEngineer --> UpdateCapability
    }


@enduml
