@startuml

left to right direction
Actor "DevOpsEngineer" as DevOpsEngineer
Actor "Software Developer" as SoftwareDeveloper
Actor "DevOpsEngineer" as DevOpsEngineer
Actor "DevOpsEngineer" as DevOpsEngineer


rectangle "Capability Manager" #00aaff {
usecase "DeployCapability" as DeployCapability
    DevOpsEngineer --> DeployCapability
    usecase "DevelopCapability" as DevelopCapability
    SoftwareDeveloper --> DevelopCapability
    usecase "RemoveCapbility" as RemoveCapbility
    DevOpsEngineer --> RemoveCapbility
    usecase "UpdateCapbility" as UpdateCapbility
    DevOpsEngineer --> UpdateCapbility
    }


@enduml
