@startuml
left to right direction


    package "sabr" as sabr {
package "sml" as sabrsml {
package "so" as sabrsmlso #aaffaa {
 component "service" as sabrsmlsoservice
 interface "ready" as sabrsmlsoserviceready
sabrsmlsoservice -- sabrsmlsoserviceready
}
}
}

    














@enduml
