@startuml
left to right direction


state "sa" as sa #pink {
state "km" as sakm #lightblue {
}
}


state "sakm" as pstatename #lightblue {
    state "Custom Function" as kmfunction {
    }
}





@enduml
