@startuml


usecase "Manage Environments" as ManageEnvironments #yellow

Actor "DevOps Engineer" as DevOpsEngineer

DevOpsEngineer --> ManageEnvironments



usecase "CreateBuildEnvironment" as CreateBuildEnvironment #lightgrey

ManageEnvironments --> CreateBuildEnvironment

usecase "UpdateBuildEnvironment" as UpdateBuildEnvironment #lightgrey

ManageEnvironments --> UpdateBuildEnvironment









@enduml
