@startuml

actor "DevOpsEngineer"


entity EventBus

box DevSecOpsManager #00aaff
    boundary dsom #white
end box


box Service Orchestrator #aaffaa
            participant provisioner
    end box


"DevOpsEngineer" -> dsom: Create Build Environment

    dsom -> "provisioner": create (name: build,file: ./templates/environment.js)

    "provisioner" --/ EventBus: environment.create



@enduml
