@startuml



package "Learning Corpus" #00aaff {

    interface "Learning Corpus" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Learning Corpus" #00aaff {
        class "AIModel" {
                 string name
                    }
    
    

}



@enduml
